# Part 1

# Series

Data Type Name - Series

There are some differences worth noting between ndarrays and Series objects. First of all, elements in NumPy arrays are accessed by their integer position, starting with zero for the first element. A pandas Series Object is more flexible as you can use define your own labeled index to index and access elements of an array. You can also use letters instead of numbers, or number an array in descending order instead of ascending order. Second, aligning data from different Series and matching labels with Series objects is more efficient than using ndarrays, for example dealing with missing values. If there are no matching labels during alignment, pandas returns NaN (not any number) so that the operation does not fail.

Source: “Learning pandas”, Michael Heyd (Packt Publishing).


Let us explore the same:

In [1]:
import numpy as np
import pandas as pd

### Creating a Series using Pandas

You could convert a list,numpy array, or dictionary to a Series in the following manner

In [2]:
labels = ['w','x','y','z']
list = [10,20,30,40]
array = np.array([10,20,30,40])
dict = {'w':10,'x':20,'y':30,'z':40}

** Using Lists**

In [3]:
pd.Series(data=list)

0    10
1    20
2    30
3    40
dtype: int64

In [4]:
pd.Series(data=list,index=labels)

w    10
x    20
y    30
z    40
dtype: int64

In [5]:
pd.Series(list,labels)

w    10
x    20
y    30
z    40
dtype: int64

** Using NumPy Arrays to create Series **

In [6]:
pd.Series(array)

0    10
1    20
2    30
3    40
dtype: int32

In [7]:
pd.Series(array,labels)

w    10
x    20
y    30
z    40
dtype: int32

** Using Dictionary to create series **

In [8]:
pd.Series(dict)

w    10
x    20
y    30
z    40
dtype: int64

## Using an Index

We shall now see how to index in a Series using the following examples of 2 series

In [9]:
sports1 = pd.Series([1,2,3,4],index = ['Cricket', 'Football','Basketball', 'Golf'])

In [10]:
sports1

Cricket       1
Football      2
Basketball    3
Golf          4
dtype: int64

In [11]:
sports2 = pd.Series([1,2,5,4],index = ['Cricket', 'Football','Baseball', 'Golf'])

In [12]:
sports2

Cricket     1
Football    2
Baseball    5
Golf        4
dtype: int64

In [13]:
sports1['Cricket']

1

Operations are then also done based off of index:

In [14]:
sports1 + sports2

Baseball      NaN
Basketball    NaN
Cricket       2.0
Football      4.0
Golf          8.0
dtype: float64

# Part 2

# DataFrames

DataFrames concept in python is similar to that of R programming language. DataFrame is a collection of Series combined together to share the same index positions.

In [15]:
from numpy.random import randn
np.random.seed(1)

In [16]:
np.random.seed(1)
dataframe = pd.DataFrame(randn(10,5),
                         index='A B C D E F G H I J'.split(),
                         columns='Score1 Score2 Score3 Score4 Score5'.split())

In [17]:
dataframe

     Score1    Score2    Score3    Score4    Score5
A  1.624345 -0.611756 -0.528172 -1.072969  0.865408
B -2.301539  1.744812 -0.761207  0.319039 -0.249370
C  1.462108 -2.060141 -0.322417 -0.384054  1.133769
D -1.099891 -0.172428 -0.877858  0.042214  0.582815
E -1.100619  1.144724  0.901591  0.502494  0.900856
F -0.683728 -0.122890 -0.935769 -0.267888  0.530355
G -0.691661 -0.396754 -0.687173 -0.845206 -0.671246
H -0.012665 -1.117310  0.234416  1.659802  0.742044
I -0.191836 -0.887629 -0.747158  1.692455  0.050808
J -0.636996  0.190915  2.100255  0.120159  0.617203

### Import CSV File as DataFrame

In [18]:
# Source - https://support.spatialkey.com/spatialkey-sample-csv-data/

real_estate = pd.read_csv('real-estate.csv')

In [19]:
real_estate.head()

,street,city,zip,state,beds,baths,sq__ft,type,sale_date,price,latitude,longitude
0,3526 HIGH ST,SACRAMENTO,95838,CA,2,1,836,Residential,Wed May 21 00:00:00 EDT 2008,59222,38.631913,-121.434879
1,51 OMAHA CT,SACRAMENTO,95823,CA,3,1,1167,Residential,Wed May 21 00:00:00 EDT 2008,68212,38.478902,-121.431028
2,2796 BRANCH ST,SACRAMENTO,95815,CA,2,1,796,Residential,Wed May 21 00:00:00 EDT 2008,68880,38.618305,-121.443839
3,2805 JANETTE WAY,SACRAMENTO,95815,CA,2,1,852,Residential,Wed May 21 00:00:00 EDT 2008,69307,38.616835,-121.439146
4,6001 MCMAHON DR,SACRAMENTO,95824,CA,2,1,797,Residential,Wed May 21 00:00:00 EDT 2008,81900,38.519470,-121.435768

In [20]:
real_estate.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 985 entries, 0 to 984
Data columns (total 12 columns):
street       985 non-null object
city         985 non-null object
zip          985 non-null int64
state        985 non-null object
beds         985 non-null int64
baths        985 non-null int64
sq__ft       985 non-null int64
type         985 non-null object
sale_date    985 non-null object
price        985 non-null int64
latitude     985 non-null float64
longitude    985 non-null float64
dtypes: float64(2), int64(5), object(5)
memory usage: 92.4+ KB

In [21]:
#Convert Object dtype to Date Time dtype

real_estate['sale_date'] = pd.to_datetime(real_estate['sale_date'],utc=True)

C:\Users\divya\Anaconda3\lib\site-packages\dateutil\parser\_parser.py:1206: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.
  category=UnknownTimezoneWarning)

In [22]:
real_estate.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 985 entries, 0 to 984
Data columns (total 12 columns):
street       985 non-null object
city         985 non-null object
zip          985 non-null int64
state        985 non-null object
beds         985 non-null int64
baths        985 non-null int64
sq__ft       985 non-null int64
type         985 non-null object
sale_date    985 non-null datetime64[ns, UTC]
price        985 non-null int64
latitude     985 non-null float64
longitude    985 non-null float64
dtypes: datetime64[ns, UTC](1), float64(2), int64(5), object(4)
memory usage: 92.4+ KB

In [23]:
real_estate.describe()

,zip,beds,baths,sq__ft,price,latitude,longitude
count,985.000000,985.000000,985.000000,985.000000,985.000000,985.000000,985.000000
mean,95750.697462,2.911675,1.776650,1314.916751,234144.263959,38.607732,-121.355982
std,85.176072,1.307932,0.895371,853.048243,138365.839085,0.145433,0.138278
min,95603.000000,0.000000,0.000000,0.000000,1551.000000,38.241514,-121.551704
25%,95660.000000,2.000000,1.000000,952.000000,145000.000000,38.482717,-121.446127
50%,95762.000000,3.000000,2.000000,1304.000000,213750.000000,38.626582,-121.376220
75%,95828.000000,4.000000,2.000000,1718.000000,300000.000000,38.695589,-121.295778
max,95864.000000,8.000000,5.000000,5822.000000,884790.000000,39.020808,-120.597599

In [24]:
real_estate.describe().round(decimals=2)

            zip    beds   baths   sq__ft      price  latitude  longitude
count    985.00  985.00  985.00   985.00     985.00    985.00     985.00
mean   95750.70    2.91    1.78  1314.92  234144.26     38.61    -121.36
std       85.18    1.31    0.90   853.05  138365.84      0.15       0.14
min    95603.00    0.00    0.00     0.00    1551.00     38.24    -121.55
25%    95660.00    2.00    1.00   952.00  145000.00     38.48    -121.45
50%    95762.00    3.00    2.00  1304.00  213750.00     38.63    -121.38
75%    95828.00    4.00    2.00  1718.00  300000.00     38.70    -121.30
max    95864.00    8.00    5.00  5822.00  884790.00     39.02    -120.60

## Selection and Indexing

Ways in which we can grab data from a DataFrame

In [25]:
real_estate['city']

0           SACRAMENTO
1           SACRAMENTO
2           SACRAMENTO
3           SACRAMENTO
4           SACRAMENTO
5           SACRAMENTO
6           SACRAMENTO
7           SACRAMENTO
8       RANCHO CORDOVA
9            RIO LINDA
10          SACRAMENTO
11          SACRAMENTO
12          SACRAMENTO
13          SACRAMENTO
14          SACRAMENTO
15          SACRAMENTO
16           RIO LINDA
17      CITRUS HEIGHTS
18          SACRAMENTO
19           RIO LINDA
20      CITRUS HEIGHTS
21          SACRAMENTO
22     NORTH HIGHLANDS
23          SACRAMENTO
24     NORTH HIGHLANDS
25            ANTELOPE
26          SACRAMENTO
27          SACRAMENTO
28          SACRAMENTO
29          SACRAMENTO
            ...
955          ROSEVILLE
956    NORTH HIGHLANDS
957               GALT
958          ELK GROVE
959           ANTELOPE
960         SACRAMENTO
961          ELK GROVE
962         SACRAMENTO
963     CITRUS HEIGHTS
964          ELK GROVE
965          ELK GROVE
966          ROSEVILLE
967         CARMICHAEL
968               GALT
969         SACRAMENTO
970         SACRAMENTO
971         SACRAMENTO
972    NORTH HIGHLANDS
973       CAMERON PARK
974         ORANGEVALE
975          ELK GROVE
976            LINCOLN
977         SACRAMENTO
978         SACRAMENTO
979          ELK GROVE
980         SACRAMENTO
981         SACRAMENTO
982     CITRUS HEIGHTS
983          ELK GROVE
984    EL DORADO HILLS
Name: city, Length: 985, dtype: object

In [26]:
# Pass a list of column names in any order necessary
real_estate[['city','zip']]

                city    zip
0         SACRAMENTO  95838
1         SACRAMENTO  95823
2         SACRAMENTO  95815
3         SACRAMENTO  95815
4         SACRAMENTO  95824
5         SACRAMENTO  95841
6         SACRAMENTO  95842
7         SACRAMENTO  95820
8     RANCHO CORDOVA  95670
9          RIO LINDA  95673
10        SACRAMENTO  95838
11        SACRAMENTO  95823
12        SACRAMENTO  95815
13        SACRAMENTO  95822
14        SACRAMENTO  95842
15        SACRAMENTO  95842
16         RIO LINDA  95673
17    CITRUS HEIGHTS  95621
18        SACRAMENTO  95833
19         RIO LINDA  95673
20    CITRUS HEIGHTS  95621
21        SACRAMENTO  95823
22   NORTH HIGHLANDS  95660
23        SACRAMENTO  95834
24   NORTH HIGHLANDS  95660
25          ANTELOPE  95843
26        SACRAMENTO  95820
27        SACRAMENTO  95832
28        SACRAMENTO  95827
29        SACRAMENTO  95828
..               ...    ...
955        ROSEVILLE  95747
956  NORTH HIGHLANDS  95660
957             GALT  95632
958        ELK GROVE  95624
959         ANTELOPE  95843
960       SACRAMENTO  95828
961        ELK GROVE  95624
962       SACRAMENTO  95828
963   CITRUS HEIGHTS  95610
964        ELK GROVE  95757
965        ELK GROVE  95758
966        ROSEVILLE  95678
967       CARMICHAEL  95608
968             GALT  95632
969       SACRAMENTO  95842
970       SACRAMENTO  95834
971       SACRAMENTO  95821
972  NORTH HIGHLANDS  95660
973     CAMERON PARK  95682
974       ORANGEVALE  95662
975        ELK GROVE  95757
976          LINCOLN  95648
977       SACRAMENTO  95823
978       SACRAMENTO  95823
979        ELK GROVE  95758
980       SACRAMENTO  95829
981       SACRAMENTO  95823
982   CITRUS HEIGHTS  95610
983        ELK GROVE  95758
984  EL DORADO HILLS  95762

[985 rows x 2 columns]

In [27]:
real_estate.index

RangeIndex(start=0, stop=985, step=1)

In [28]:
real_estate.columns

Index(['street', 'city', 'zip', 'state', 'beds', 'baths', 'sq__ft', 'type',
       'sale_date', 'price', 'latitude', 'longitude'],
      dtype='object')

DataFrame Columns are nothing but a Series each

In [29]:
type(real_estate['city'])

pandas.core.series.Series

**Adding a new column to the DataFrame**

In [30]:
# Convert Sq feet to Sq Meters

#Formula	
#divide the area value by 10.764


real_estate['sq__mt'] = real_estate['sq__ft'] / 10.764

In [31]:
real_estate.head()

,street,city,zip,state,beds,baths,sq__ft,type,sale_date,price,latitude,longitude,sq__mt
0,3526 HIGH ST,SACRAMENTO,95838,CA,2,1,836,Residential,2008-05-21 00:00:00+00:00,59222,38.631913,-121.434879,77.666295
1,51 OMAHA CT,SACRAMENTO,95823,CA,3,1,1167,Residential,2008-05-21 00:00:00+00:00,68212,38.478902,-121.431028,108.416945
2,2796 BRANCH ST,SACRAMENTO,95815,CA,2,1,796,Residential,2008-05-21 00:00:00+00:00,68880,38.618305,-121.443839,73.950204
3,2805 JANETTE WAY,SACRAMENTO,95815,CA,2,1,852,Residential,2008-05-21 00:00:00+00:00,69307,38.616835,-121.439146,79.152731
4,6001 MCMAHON DR,SACRAMENTO,95824,CA,2,1,797,Residential,2008-05-21 00:00:00+00:00,81900,38.519470,-121.435768,74.043107

** Removing Columns from DataFrame**

In [32]:
real_estate.drop('sq__mt',axis=1)              # Use axis=0 for dropping rows and axis=1 for dropping columns

,street,city,zip,state,beds,baths,sq__ft,type,sale_date,price,latitude,longitude
0,3526 HIGH ST,SACRAMENTO,95838,CA,2,1,836,Residential,2008-05-21 00:00:00+00:00,59222,38.631913,-121.434879
1,51 OMAHA CT,SACRAMENTO,95823,CA,3,1,1167,Residential,2008-05-21 00:00:00+00:00,68212,38.478902,-121.431028
2,2796 BRANCH ST,SACRAMENTO,95815,CA,2,1,796,Residential,2008-05-21 00:00:00+00:00,68880,38.618305,-121.443839
3,2805 JANETTE WAY,SACRAMENTO,95815,CA,2,1,852,Residential,2008-05-21 00:00:00+00:00,69307,38.616835,-121.439146
4,6001 MCMAHON DR,SACRAMENTO,95824,CA,2,1,797,Residential,2008-05-21 00:00:00+00:00,81900,38.519470,-121.435768
5,5828 PEPPERMILL CT,SACRAMENTO,95841,CA,3,1,1122,Condo,2008-05-21 00:00:00+00:00,89921,38.662595,-121.327813
6,6048 OGDEN NASH WAY,SACRAMENTO,95842,CA,3,2,1104,Residential,2008-05-21 00:00:00+00:00,90895,38.681659,-121.351705
7,2561 19TH AVE,SACRAMENTO,95820,CA,3,1,1177,Residential,2008-05-21 00:00:00+00:00,91002,38.535092,-121.481367
8,11150 TRINITY RIVER DR Unit 114,RANCHO CORDOVA,95670,CA,2,2,941,Condo,2008-05-21 00:00:00+00:00,94905,38.621188,-121.270555
9,7325 10TH ST,RIO LINDA,95673,CA,3,2,1146,Residential,2008-05-21 00:00:00+00:00,98937,38.700909,-121.442979
10,645 MORRISON AVE,SACRAMENTO,95838,CA,3,2,909,Residential,2008-05-21 00:00:00+00:00,100309,38.637663,-121.451520
11,4085 FAWN CIR,SACRAMENTO,95823,CA,3,2,1289,Residential,2008-05-21 00:00:00+00:00,106250,38.470746,-121.458918
12,2930 LA ROSA RD,SACRAMENTO,95815,CA,1,1,871,Residential,2008-05-21 00:00:00+00:00,106852,38.618698,-121.435833
13,2113 KIRK WAY,SACRAMENTO,95822,CA,3,1,1020,Residential,2008-05-21 00:00:00+00:00,107502,38.482215,-121.492603
14,4533 LOCH HAVEN WAY,SACRAMENTO,95842,CA,2,2,1022,Residential,2008-05-21 00:00:00+00:00,108750,38.672914,-121.359340
15,7340 HAMDEN PL,SACRAMENTO,95842,CA,2,2,1134,Condo,2008-05-21 00:00:00+00:00,110700,38.700051,-121.351278
16,6715 6TH ST,RIO LINDA,95673,CA,2,1,844,Residential,2008-05-21 00:00:00+00:00,113263,38.689591,-121.452239
17,6236 LONGFORD DR Unit 1,CITRUS HEIGHTS,95621,CA,2,1,795,Condo,2008-05-21 00:00:00+00:00,116250,38.679776,-121.314089
18,250 PERALTA AVE,SACRAMENTO,95833,CA,2,1,588,Residential,2008-05-21 00:00:00+00:00,120000,38.612099,-121.469095
19,113 LEEWILL AVE,RIO LINDA,95673,CA,3,2,1356,Residential,2008-05-21 00:00:00+00:00,121630,38.689999,-121.463220
20,6118 STONEHAND AVE,CITRUS HEIGHTS,95621,CA,3,2,1118,Residential,2008-05-21 00:00:00+00:00,122000,38.707851,-121.320707
21,4882 BANDALIN WAY,SACRAMENTO,95823,CA,4,2,1329,Residential,2008-05-21 00:00:00+00:00,122682,38.468173,-121.444071
22,7511 OAKVALE CT,NORTH HIGHLANDS,95660,CA,4,2,1240,Residential,2008-05-21 00:00:00+00:00,123000,38.702792,-121.382210
23,9 PASTURE CT,SACRAMENTO,95834,CA,3,2,1601,Residential,2008-05-21 00:00:00+00:00,124100,38.628631,-121.488097
24,3729 BAINBRIDGE DR,NORTH HIGHLANDS,95660,CA,3,2,901,Residential,2008-05-21 00:00:00+00:00,125000,38.701499,-121.376220
25,3828 BLACKFOOT WAY,ANTELOPE,95843,CA,3,2,1088,Residential,2008-05-21 00:00:00+00:00,126640,38.709740,-121.373770
26,4108 NORTON WAY,SACRAMENTO,95820,CA,3,1,963,Residential,2008-05-21 00:00:00+00:00,127281,38.537526,-121.478315
27,1469 JANRICK AVE,SACRAMENTO,95832,CA,3,2,1119,Residential,2008-05-21 00:00:00+00:00,129000,38.476472,-121.501711
28,9861 CULP WAY,SACRAMENTO,95827,CA,4,2,1380,Residential,2008-05-21 00:00:00+00:00,131200,38.558423,-121.327948
29,7825 CREEK VALLEY CIR,SACRAMENTO,95828,CA,3,2,1248,Residential,2008-05-21 00:00:00+00:00,132000,38.472122,-121.404199
...,...,...,...,...,...,...,...,...,...,...,...,...
955,2100 BEATTY WAY,ROSEVILLE,95747,CA,3,2,1371,Residential,2008-05-15 00:00:00+00:00,208250,38.737882,-121.308142
956,6920 GILLINGHAM WAY,NORTH HIGHLANDS,95660,CA,3,1,1310,Residential,2008-05-15 00:00:00+00:00,208318,38.694279,-121.373395
957,82 WILDFLOWER DR,GALT,95632,CA,3,2,1262,Residential,2008-05-15 00:00:00+00:00,209347,38.259708,-121.311616
958,8652 BANTON CIR,ELK GROVE,95624,CA,4,2,1740,Residential,2008-05-15 00:00:00+00:00,211500,38.444000,-121.370993
959,8428 MISTY PASS WAY,ANTELOPE,95843,CA,3,2,1517,Residential,2008-05-15 00:00:00+00:00,212000,38.722959,-121.347115
960,7958 ROSEVIEW WAY,SACRAMENTO,95828,CA,3,2,1450,Residential,2008-05-15 00:00:00+00:00,213000,38.467836,-121.410366
961,9020 LUKEN CT,ELK GROVE,95624,CA,3,2,1416,Residential,2008-05-15 00:00:00+00:00,216000,38.451398,-121.366614
962,7809 VALLECITOS WAY,SACRAMENTO,95828,CA,3,1,888,Residential,2008-05-15 00:00:00+00:00,216021,38.508217,-121.411207
963,8445 OLD AUBURN RD,CITRUS HEIGHTS,95610,CA,3,2,1882,Residential,2008-05-15 00:00:00+00:00,219000,38.715423,-121.246743
964,10085 ATKINS DR,ELK GROVE,95757,CA,3,2,1302,Residential,2008-05-15 00:00:00+00:00,219794,38.390893,-121.437821
965,9185 CERROLINDA CIR,ELK GROVE,95758,CA,3,2,1418,Residential,2008-05-15 00:00:00+00:00,220000,38.424497,-121.426595
966,9197 CORTINA CIR,ROSEVILLE,95678,CA,3,2,0,Condo,2008-05-15 00:00:00+00:00,220000,38.793152,-121.290025
967,5429 HESPER WAY,CARMICHAEL,95608,CA,4,2,1319,Residential,2008-05-15 00:00:00+00:00,220000,38.665104,-121.315901
968,1178 WARMWOOD CT,GALT,95632,CA,4,2,1770,Residential,2008-05-15 00:00:00+00:00,220000,38.289544,-121.284607
969,4900 ELUDE CT,SACRAMENTO,95842,CA,4,2,1627,Residential,2008-05-15 00:00:00+00:00,223000,38.696740,-121.350519
970,3557 SODA WAY,SACRAMENTO,95834,CA,0,0,0,Residential,2008-05-15 00:00:00+00:00,224000,38.631026,-121.501879
971,3528 SAINT GEORGE DR,SACRAMENTO,95821,CA,3,1,1040,Residential,2008-05-15 00:00:00+00:00,224000,38.629468,-121.376445
972,7381 WASHBURN WAY,NORTH HIGHLANDS,95660,CA,3,1,960,Residential,2008-05-15 00:00:00+00:00,224252,38.703550,-121.375103
973,2181 WINTERHAVEN CIR,CAMERON PARK,95682,CA,3,2,0,Residential,2008-05-15 00:00:00+00:00,224500,38.697570,-120.995739
974,7540 HICKORY AVE,ORANGEVALE,95662,CA,3,1,1456,Residential,2008-05-15 00:00:00+00:00,225000,38.703056,-121.235221
975,5024 CHAMBERLIN CIR,ELK GROVE,95757,CA,3,2,1450,Residential,2008-05-15 00:00:00+00:00,228000,38.389756,-121.446246
976,2400 INVERNESS DR,LINCOLN,95648,CA,3,2,1358,Residential,2008-05-15 00:00:00+00:00,229027,38.897814,-121.324691
977,5 BISHOPGATE CT,SACRAMENTO,95823,CA,4,2,1329,Residential,2008-05-15 00:00:00+00:00,229500,38.467936,-121.445477
978,5601 REXLEIGH DR,SACRAMENTO,95823,CA,4,2,1715,Residential,2008-05-15 00:00:00+00:00,230000,38.445342,-121.441504
979,1909 YARNELL WAY,ELK GROVE,95758,CA,3,2,1262,Residential,2008-05-15 00:00:00+00:00,230000,38.417382,-121.484325
980,9169 GARLINGTON CT,SACRAMENTO,95829,CA,4,3,2280,Residential,2008-05-15 00:00:00+00:00,232425,38.457679,-121.359620
981,6932 RUSKUT WAY,SACRAMENTO,95823,CA,3,2,1477,Residential,2008-05-15 00:00:00+00:00,234000,38.499893,-121.458890
982,7933 DAFFODIL WAY,CITRUS HEIGHTS,95610,CA,3,2,1216,Residential,2008-05-15 00:00:00+00:00,235000,38.708824,-121.256803
983,8304 RED FOX WAY,ELK GROVE,95758,CA,4,2,1685,Residential,2008-05-15 00:00:00+00:00,235301,38.417000,-121.397424
984,3882 YELLOWSTONE LN,EL DORADO HILLS,95762,CA,3,2,1362,Residential,2008-05-15 00:00:00+00:00,235738,38.655245,-121.075915

In [33]:
# column is not dropped unless inplace input is TRUE
real_estate.head()

,street,city,zip,state,beds,baths,sq__ft,type,sale_date,price,latitude,longitude,sq__mt
0,3526 HIGH ST,SACRAMENTO,95838,CA,2,1,836,Residential,2008-05-21 00:00:00+00:00,59222,38.631913,-121.434879,77.666295
1,51 OMAHA CT,SACRAMENTO,95823,CA,3,1,1167,Residential,2008-05-21 00:00:00+00:00,68212,38.478902,-121.431028,108.416945
2,2796 BRANCH ST,SACRAMENTO,95815,CA,2,1,796,Residential,2008-05-21 00:00:00+00:00,68880,38.618305,-121.443839,73.950204
3,2805 JANETTE WAY,SACRAMENTO,95815,CA,2,1,852,Residential,2008-05-21 00:00:00+00:00,69307,38.616835,-121.439146,79.152731
4,6001 MCMAHON DR,SACRAMENTO,95824,CA,2,1,797,Residential,2008-05-21 00:00:00+00:00,81900,38.519470,-121.435768,74.043107

In [34]:
real_estate.drop('sq__mt',axis=1,inplace=True)

In [32]:
real_estate.head()

,street,city,zip,state,beds,baths,sq__ft,type,sale_date,price,latitude,longitude
0,3526 HIGH ST,SACRAMENTO,95838,CA,2,1,836,Residential,Wed May 21 00:00:00 EDT 2008,59222,38.631913,-121.434879
1,51 OMAHA CT,SACRAMENTO,95823,CA,3,1,1167,Residential,Wed May 21 00:00:00 EDT 2008,68212,38.478902,-121.431028
2,2796 BRANCH ST,SACRAMENTO,95815,CA,2,1,796,Residential,Wed May 21 00:00:00 EDT 2008,68880,38.618305,-121.443839
3,2805 JANETTE WAY,SACRAMENTO,95815,CA,2,1,852,Residential,Wed May 21 00:00:00 EDT 2008,69307,38.616835,-121.439146
4,6001 MCMAHON DR,SACRAMENTO,95824,CA,2,1,797,Residential,Wed May 21 00:00:00 EDT 2008,81900,38.519470,-121.435768

Dropping rows using axis=0

In [33]:
real_estate.drop(1,axis=0)      # Row will also be dropped only if inplace=TRUE is given as input

,street,city,zip,state,beds,baths,sq__ft,type,sale_date,price,latitude,longitude
0,3526 HIGH ST,SACRAMENTO,95838,CA,2,1,836,Residential,Wed May 21 00:00:00 EDT 2008,59222,38.631913,-121.434879
2,2796 BRANCH ST,SACRAMENTO,95815,CA,2,1,796,Residential,Wed May 21 00:00:00 EDT 2008,68880,38.618305,-121.443839
3,2805 JANETTE WAY,SACRAMENTO,95815,CA,2,1,852,Residential,Wed May 21 00:00:00 EDT 2008,69307,38.616835,-121.439146
4,6001 MCMAHON DR,SACRAMENTO,95824,CA,2,1,797,Residential,Wed May 21 00:00:00 EDT 2008,81900,38.519470,-121.435768
5,5828 PEPPERMILL CT,SACRAMENTO,95841,CA,3,1,1122,Condo,Wed May 21 00:00:00 EDT 2008,89921,38.662595,-121.327813
6,6048 OGDEN NASH WAY,SACRAMENTO,95842,CA,3,2,1104,Residential,Wed May 21 00:00:00 EDT 2008,90895,38.681659,-121.351705
7,2561 19TH AVE,SACRAMENTO,95820,CA,3,1,1177,Residential,Wed May 21 00:00:00 EDT 2008,91002,38.535092,-121.481367
8,11150 TRINITY RIVER DR Unit 114,RANCHO CORDOVA,95670,CA,2,2,941,Condo,Wed May 21 00:00:00 EDT 2008,94905,38.621188,-121.270555
9,7325 10TH ST,RIO LINDA,95673,CA,3,2,1146,Residential,Wed May 21 00:00:00 EDT 2008,98937,38.700909,-121.442979
10,645 MORRISON AVE,SACRAMENTO,95838,CA,3,2,909,Residential,Wed May 21 00:00:00 EDT 2008,100309,38.637663,-121.451520
11,4085 FAWN CIR,SACRAMENTO,95823,CA,3,2,1289,Residential,Wed May 21 00:00:00 EDT 2008,106250,38.470746,-121.458918
12,2930 LA ROSA RD,SACRAMENTO,95815,CA,1,1,871,Residential,Wed May 21 00:00:00 EDT 2008,106852,38.618698,-121.435833
13,2113 KIRK WAY,SACRAMENTO,95822,CA,3,1,1020,Residential,Wed May 21 00:00:00 EDT 2008,107502,38.482215,-121.492603
14,4533 LOCH HAVEN WAY,SACRAMENTO,95842,CA,2,2,1022,Residential,Wed May 21 00:00:00 EDT 2008,108750,38.672914,-121.359340
15,7340 HAMDEN PL,SACRAMENTO,95842,CA,2,2,1134,Condo,Wed May 21 00:00:00 EDT 2008,110700,38.700051,-121.351278
16,6715 6TH ST,RIO LINDA,95673,CA,2,1,844,Residential,Wed May 21 00:00:00 EDT 2008,113263,38.689591,-121.452239
17,6236 LONGFORD DR Unit 1,CITRUS HEIGHTS,95621,CA,2,1,795,Condo,Wed May 21 00:00:00 EDT 2008,116250,38.679776,-121.314089
18,250 PERALTA AVE,SACRAMENTO,95833,CA,2,1,588,Residential,Wed May 21 00:00:00 EDT 2008,120000,38.612099,-121.469095
19,113 LEEWILL AVE,RIO LINDA,95673,CA,3,2,1356,Residential,Wed May 21 00:00:00 EDT 2008,121630,38.689999,-121.463220
20,6118 STONEHAND AVE,CITRUS HEIGHTS,95621,CA,3,2,1118,Residential,Wed May 21 00:00:00 EDT 2008,122000,38.707851,-121.320707
21,4882 BANDALIN WAY,SACRAMENTO,95823,CA,4,2,1329,Residential,Wed May 21 00:00:00 EDT 2008,122682,38.468173,-121.444071
22,7511 OAKVALE CT,NORTH HIGHLANDS,95660,CA,4,2,1240,Residential,Wed May 21 00:00:00 EDT 2008,123000,38.702792,-121.382210
23,9 PASTURE CT,SACRAMENTO,95834,CA,3,2,1601,Residential,Wed May 21 00:00:00 EDT 2008,124100,38.628631,-121.488097
24,3729 BAINBRIDGE DR,NORTH HIGHLANDS,95660,CA,3,2,901,Residential,Wed May 21 00:00:00 EDT 2008,125000,38.701499,-121.376220
25,3828 BLACKFOOT WAY,ANTELOPE,95843,CA,3,2,1088,Residential,Wed May 21 00:00:00 EDT 2008,126640,38.709740,-121.373770
26,4108 NORTON WAY,SACRAMENTO,95820,CA,3,1,963,Residential,Wed May 21 00:00:00 EDT 2008,127281,38.537526,-121.478315
27,1469 JANRICK AVE,SACRAMENTO,95832,CA,3,2,1119,Residential,Wed May 21 00:00:00 EDT 2008,129000,38.476472,-121.501711
28,9861 CULP WAY,SACRAMENTO,95827,CA,4,2,1380,Residential,Wed May 21 00:00:00 EDT 2008,131200,38.558423,-121.327948
29,7825 CREEK VALLEY CIR,SACRAMENTO,95828,CA,3,2,1248,Residential,Wed May 21 00:00:00 EDT 2008,132000,38.472122,-121.404199
30,5201 LAGUNA OAKS DR Unit 140,ELK GROVE,95758,CA,2,2,1039,Condo,Wed May 21 00:00:00 EDT 2008,133000,38.423251,-121.444489
...,...,...,...,...,...,...,...,...,...,...,...,...
955,2100 BEATTY WAY,ROSEVILLE,95747,CA,3,2,1371,Residential,Thu May 15 00:00:00 EDT 2008,208250,38.737882,-121.308142
956,6920 GILLINGHAM WAY,NORTH HIGHLANDS,95660,CA,3,1,1310,Residential,Thu May 15 00:00:00 EDT 2008,208318,38.694279,-121.373395
957,82 WILDFLOWER DR,GALT,95632,CA,3,2,1262,Residential,Thu May 15 00:00:00 EDT 2008,209347,38.259708,-121.311616
958,8652 BANTON CIR,ELK GROVE,95624,CA,4,2,1740,Residential,Thu May 15 00:00:00 EDT 2008,211500,38.444000,-121.370993
959,8428 MISTY PASS WAY,ANTELOPE,95843,CA,3,2,1517,Residential,Thu May 15 00:00:00 EDT 2008,212000,38.722959,-121.347115
960,7958 ROSEVIEW WAY,SACRAMENTO,95828,CA,3,2,1450,Residential,Thu May 15 00:00:00 EDT 2008,213000,38.467836,-121.410366
961,9020 LUKEN CT,ELK GROVE,95624,CA,3,2,1416,Residential,Thu May 15 00:00:00 EDT 2008,216000,38.451398,-121.366614
962,7809 VALLECITOS WAY,SACRAMENTO,95828,CA,3,1,888,Residential,Thu May 15 00:00:00 EDT 2008,216021,38.508217,-121.411207
963,8445 OLD AUBURN RD,CITRUS HEIGHTS,95610,CA,3,2,1882,Residential,Thu May 15 00:00:00 EDT 2008,219000,38.715423,-121.246743
964,10085 ATKINS DR,ELK GROVE,95757,CA,3,2,1302,Residential,Thu May 15 00:00:00 EDT 2008,219794,38.390893,-121.437821
965,9185 CERROLINDA CIR,ELK GROVE,95758,CA,3,2,1418,Residential,Thu May 15 00:00:00 EDT 2008,220000,38.424497,-121.426595
966,9197 CORTINA CIR,ROSEVILLE,95678,CA,3,2,0,Condo,Thu May 15 00:00:00 EDT 2008,220000,38.793152,-121.290025
967,5429 HESPER WAY,CARMICHAEL,95608,CA,4,2,1319,Residential,Thu May 15 00:00:00 EDT 2008,220000,38.665104,-121.315901
968,1178 WARMWOOD CT,GALT,95632,CA,4,2,1770,Residential,Thu May 15 00:00:00 EDT 2008,220000,38.289544,-121.284607
969,4900 ELUDE CT,SACRAMENTO,95842,CA,4,2,1627,Residential,Thu May 15 00:00:00 EDT 2008,223000,38.696740,-121.350519
970,3557 SODA WAY,SACRAMENTO,95834,CA,0,0,0,Residential,Thu May 15 00:00:00 EDT 2008,224000,38.631026,-121.501879
971,3528 SAINT GEORGE DR,SACRAMENTO,95821,CA,3,1,1040,Residential,Thu May 15 00:00:00 EDT 2008,224000,38.629468,-121.376445
972,7381 WASHBURN WAY,NORTH HIGHLANDS,95660,CA,3,1,960,Residential,Thu May 15 00:00:00 EDT 2008,224252,38.703550,-121.375103
973,2181 WINTERHAVEN CIR,CAMERON PARK,95682,CA,3,2,0,Residential,Thu May 15 00:00:00 EDT 2008,224500,38.697570,-120.995739
974,7540 HICKORY AVE,ORANGEVALE,95662,CA,3,1,1456,Residential,Thu May 15 00:00:00 EDT 2008,225000,38.703056,-121.235221
975,5024 CHAMBERLIN CIR,ELK GROVE,95757,CA,3,2,1450,Residential,Thu May 15 00:00:00 EDT 2008,228000,38.389756,-121.446246
976,2400 INVERNESS DR,LINCOLN,95648,CA,3,2,1358,Residential,Thu May 15 00:00:00 EDT 2008,229027,38.897814,-121.324691
977,5 BISHOPGATE CT,SACRAMENTO,95823,CA,4,2,1329,Residential,Thu May 15 00:00:00 EDT 2008,229500,38.467936,-121.445477
978,5601 REXLEIGH DR,SACRAMENTO,95823,CA,4,2,1715,Residential,Thu May 15 00:00:00 EDT 2008,230000,38.445342,-121.441504
979,1909 YARNELL WAY,ELK GROVE,95758,CA,3,2,1262,Residential,Thu May 15 00:00:00 EDT 2008,230000,38.417382,-121.484325
980,9169 GARLINGTON CT,SACRAMENTO,95829,CA,4,3,2280,Residential,Thu May 15 00:00:00 EDT 2008,232425,38.457679,-121.359620
981,6932 RUSKUT WAY,SACRAMENTO,95823,CA,3,2,1477,Residential,Thu May 15 00:00:00 EDT 2008,234000,38.499893,-121.458890
982,7933 DAFFODIL WAY,CITRUS HEIGHTS,95610,CA,3,2,1216,Residential,Thu May 15 00:00:00 EDT 2008,235000,38.708824,-121.256803
983,8304 RED FOX WAY,ELK GROVE,95758,CA,4,2,1685,Residential,Thu May 15 00:00:00 EDT 2008,235301,38.417000,-121.397424
984,3882 YELLOWSTONE LN,EL DORADO HILLS,95762,CA,3,2,1362,Residential,Thu May 15 00:00:00 EDT 2008,235738,38.655245,-121.075915

**Selecting Rows**

You could use the .loc function as an alternative if there are custom row index values in the dataframe.

In [35]:
real_estate.iloc[2]

street                  2796 BRANCH ST
city                        SACRAMENTO
zip                              95815
state                               CA
beds                                 2
baths                                1
sq__ft                             796
type                       Residential
sale_date    2008-05-21 00:00:00+00:00
price                            68880
latitude                       38.6183
longitude                     -121.444
Name: 2, dtype: object

In [38]:
real_estate.iloc[3:5]

,street,city,zip,state,beds,baths,sq__ft,type,sale_date,price,latitude,longitude
3,2805 JANETTE WAY,SACRAMENTO,95815,CA,2,1,852,Residential,2008-05-21 00:00:00+00:00,69307,38.616835,-121.439146
4,6001 MCMAHON DR,SACRAMENTO,95824,CA,2,1,797,Residential,2008-05-21 00:00:00+00:00,81900,38.519470,-121.435768

**Selecting subset of rows and columns using loc function**

### Conditional Selection

Similar to NumPy, we can make conditional selections using Brackets

In [40]:
real_estate['sq__ft'] > 4000

0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
       ...
955    False
956    False
957    False
958    False
959    False
960    False
961    False
962    False
963    False
964    False
965    False
966    False
967    False
968    False
969    False
970    False
971    False
972    False
973    False
974    False
975    False
976    False
977    False
978    False
979    False
980    False
981    False
982    False
983    False
984    False
Name: sq__ft, Length: 985, dtype: bool

In [41]:
real_estate[real_estate['sq__ft'] > 4000]

,street,city,zip,state,beds,baths,sq__ft,type,sale_date,price,latitude,longitude
534,5201 BLOSSOM RANCH DR,ELK GROVE,95757,CA,4,4,4303,Residential,2008-05-19 00:00:00+00:00,450000,38.399436,-121.444041
535,3027 PALMATE WAY,SACRAMENTO,95834,CA,5,3,4246,Residential,2008-05-19 00:00:00+00:00,452000,38.628955,-121.529269
864,9401 BARREL RACER CT,WILTON,95693,CA,4,3,4400,Residential,2008-05-16 00:00:00+00:00,884790,38.415298,-121.194858
866,14151 INDIO DR,SLOUGHHOUSE,95683,CA,3,4,5822,Residential,2008-05-16 00:00:00+00:00,2000,38.490447,-121.129337

In [51]:
real_estate[real_estate['sq__ft'] > 4000]['city']

534      ELK GROVE
535     SACRAMENTO
864         WILTON
866    SLOUGHHOUSE
Name: city, dtype: object

For multiple conditions you can use | and & with parenthesis

In [42]:
real_estate[(real_estate['sq__ft'] > 4000) & (real_estate['beds'] > 4)]

,street,city,zip,state,beds,baths,sq__ft,type,sale_date,price,latitude,longitude
535,3027 PALMATE WAY,SACRAMENTO,95834,CA,5,3,4246,Residential,2008-05-19 00:00:00+00:00,452000,38.628955,-121.529269

# Part 3

# Missing Data

Methods to deal with missing data in Pandas

In [68]:
real_estate_na = pd.read_csv('real-estate-na.csv')

In [69]:
real_estate_na.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 985 entries, 0 to 984
Data columns (total 12 columns):
street       941 non-null object
city         985 non-null object
zip          985 non-null int64
state        985 non-null object
beds         985 non-null int64
baths        985 non-null int64
sq__ft       985 non-null int64
type         985 non-null object
sale_date    985 non-null object
price        965 non-null float64
latitude     985 non-null float64
longitude    985 non-null float64
dtypes: float64(3), int64(4), object(5)
memory usage: 92.4+ KB

In [70]:
real_estate_na.dropna()

,street,city,zip,state,beds,baths,sq__ft,type,sale_date,price,latitude,longitude
0,3526 HIGH ST,SACRAMENTO,95838,CA,2,1,836,Residential,Wed May 21 00:00:00 EDT 2008,59222.0,38.631913,-121.434879
1,51 OMAHA CT,SACRAMENTO,95823,CA,3,1,1167,Residential,Wed May 21 00:00:00 EDT 2008,68212.0,38.478902,-121.431028
3,2805 JANETTE WAY,SACRAMENTO,95815,CA,2,1,852,Residential,Wed May 21 00:00:00 EDT 2008,69307.0,38.616835,-121.439146
4,6001 MCMAHON DR,SACRAMENTO,95824,CA,2,1,797,Residential,Wed May 21 00:00:00 EDT 2008,81900.0,38.519470,-121.435768
5,5828 PEPPERMILL CT,SACRAMENTO,95841,CA,3,1,1122,Condo,Wed May 21 00:00:00 EDT 2008,89921.0,38.662595,-121.327813
6,6048 OGDEN NASH WAY,SACRAMENTO,95842,CA,3,2,1104,Residential,Wed May 21 00:00:00 EDT 2008,90895.0,38.681659,-121.351705
7,2561 19TH AVE,SACRAMENTO,95820,CA,3,1,1177,Residential,Wed May 21 00:00:00 EDT 2008,91002.0,38.535092,-121.481367
8,11150 TRINITY RIVER DR Unit 114,RANCHO CORDOVA,95670,CA,2,2,941,Condo,Wed May 21 00:00:00 EDT 2008,94905.0,38.621188,-121.270555
9,7325 10TH ST,RIO LINDA,95673,CA,3,2,1146,Residential,Wed May 21 00:00:00 EDT 2008,98937.0,38.700909,-121.442979
10,645 MORRISON AVE,SACRAMENTO,95838,CA,3,2,909,Residential,Wed May 21 00:00:00 EDT 2008,100309.0,38.637663,-121.451520
11,4085 FAWN CIR,SACRAMENTO,95823,CA,3,2,1289,Residential,Wed May 21 00:00:00 EDT 2008,106250.0,38.470746,-121.458918
12,2930 LA ROSA RD,SACRAMENTO,95815,CA,1,1,871,Residential,Wed May 21 00:00:00 EDT 2008,106852.0,38.618698,-121.435833
13,2113 KIRK WAY,SACRAMENTO,95822,CA,3,1,1020,Residential,Wed May 21 00:00:00 EDT 2008,107502.0,38.482215,-121.492603
14,4533 LOCH HAVEN WAY,SACRAMENTO,95842,CA,2,2,1022,Residential,Wed May 21 00:00:00 EDT 2008,108750.0,38.672914,-121.359340
15,7340 HAMDEN PL,SACRAMENTO,95842,CA,2,2,1134,Condo,Wed May 21 00:00:00 EDT 2008,110700.0,38.700051,-121.351278
16,6715 6TH ST,RIO LINDA,95673,CA,2,1,844,Residential,Wed May 21 00:00:00 EDT 2008,113263.0,38.689591,-121.452239
17,6236 LONGFORD DR Unit 1,CITRUS HEIGHTS,95621,CA,2,1,795,Condo,Wed May 21 00:00:00 EDT 2008,116250.0,38.679776,-121.314089
18,250 PERALTA AVE,SACRAMENTO,95833,CA,2,1,588,Residential,Wed May 21 00:00:00 EDT 2008,120000.0,38.612099,-121.469095
19,113 LEEWILL AVE,RIO LINDA,95673,CA,3,2,1356,Residential,Wed May 21 00:00:00 EDT 2008,121630.0,38.689999,-121.463220
20,6118 STONEHAND AVE,CITRUS HEIGHTS,95621,CA,3,2,1118,Residential,Wed May 21 00:00:00 EDT 2008,122000.0,38.707851,-121.320707
21,4882 BANDALIN WAY,SACRAMENTO,95823,CA,4,2,1329,Residential,Wed May 21 00:00:00 EDT 2008,122682.0,38.468173,-121.444071
22,7511 OAKVALE CT,NORTH HIGHLANDS,95660,CA,4,2,1240,Residential,Wed May 21 00:00:00 EDT 2008,123000.0,38.702792,-121.382210
24,3729 BAINBRIDGE DR,NORTH HIGHLANDS,95660,CA,3,2,901,Residential,Wed May 21 00:00:00 EDT 2008,125000.0,38.701499,-121.376220
25,3828 BLACKFOOT WAY,ANTELOPE,95843,CA,3,2,1088,Residential,Wed May 21 00:00:00 EDT 2008,126640.0,38.709740,-121.373770
26,4108 NORTON WAY,SACRAMENTO,95820,CA,3,1,963,Residential,Wed May 21 00:00:00 EDT 2008,127281.0,38.537526,-121.478315
27,1469 JANRICK AVE,SACRAMENTO,95832,CA,3,2,1119,Residential,Wed May 21 00:00:00 EDT 2008,129000.0,38.476472,-121.501711
28,9861 CULP WAY,SACRAMENTO,95827,CA,4,2,1380,Residential,Wed May 21 00:00:00 EDT 2008,131200.0,38.558423,-121.327948
29,7825 CREEK VALLEY CIR,SACRAMENTO,95828,CA,3,2,1248,Residential,Wed May 21 00:00:00 EDT 2008,132000.0,38.472122,-121.404199
30,5201 LAGUNA OAKS DR Unit 140,ELK GROVE,95758,CA,2,2,1039,Condo,Wed May 21 00:00:00 EDT 2008,133000.0,38.423251,-121.444489
31,6768 MEDORA DR,NORTH HIGHLANDS,95660,CA,3,2,1152,Residential,Wed May 21 00:00:00 EDT 2008,134555.0,38.691161,-121.371920
...,...,...,...,...,...,...,...,...,...,...,...,...
953,5209 LAGUNA CREST WAY,ELK GROVE,95758,CA,2,2,1189,Residential,Thu May 15 00:00:00 EDT 2008,207000.0,38.424421,-121.443915
954,416 LEITCH AVE,SACRAMENTO,95815,CA,2,1,795,Residential,Thu May 15 00:00:00 EDT 2008,207973.0,38.612694,-121.456669
955,2100 BEATTY WAY,ROSEVILLE,95747,CA,3,2,1371,Residential,Thu May 15 00:00:00 EDT 2008,208250.0,38.737882,-121.308142
956,6920 GILLINGHAM WAY,NORTH HIGHLANDS,95660,CA,3,1,1310,Residential,Thu May 15 00:00:00 EDT 2008,208318.0,38.694279,-121.373395
957,82 WILDFLOWER DR,GALT,95632,CA,3,2,1262,Residential,Thu May 15 00:00:00 EDT 2008,209347.0,38.259708,-121.311616
958,8652 BANTON CIR,ELK GROVE,95624,CA,4,2,1740,Residential,Thu May 15 00:00:00 EDT 2008,211500.0,38.444000,-121.370993
959,8428 MISTY PASS WAY,ANTELOPE,95843,CA,3,2,1517,Residential,Thu May 15 00:00:00 EDT 2008,212000.0,38.722959,-121.347115
960,7958 ROSEVIEW WAY,SACRAMENTO,95828,CA,3,2,1450,Residential,Thu May 15 00:00:00 EDT 2008,213000.0,38.467836,-121.410366
961,9020 LUKEN CT,ELK GROVE,95624,CA,3,2,1416,Residential,Thu May 15 00:00:00 EDT 2008,216000.0,38.451398,-121.366614
962,7809 VALLECITOS WAY,SACRAMENTO,95828,CA,3,1,888,Residential,Thu May 15 00:00:00 EDT 2008,216021.0,38.508217,-121.411207
963,8445 OLD AUBURN RD,CITRUS HEIGHTS,95610,CA,3,2,1882,Residential,Thu May 15 00:00:00 EDT 2008,219000.0,38.715423,-121.246743
964,10085 ATKINS DR,ELK GROVE,95757,CA,3,2,1302,Residential,Thu May 15 00:00:00 EDT 2008,219794.0,38.390893,-121.437821
965,9185 CERROLINDA CIR,ELK GROVE,95758,CA,3,2,1418,Residential,Thu May 15 00:00:00 EDT 2008,220000.0,38.424497,-121.426595
966,9197 CORTINA CIR,ROSEVILLE,95678,CA,3,2,0,Condo,Thu May 15 00:00:00 EDT 2008,220000.0,38.793152,-121.290025
967,5429 HESPER WAY,CARMICHAEL,95608,CA,4,2,1319,Residential,Thu May 15 00:00:00 EDT 2008,220000.0,38.665104,-121.315901
969,4900 ELUDE CT,SACRAMENTO,95842,CA,4,2,1627,Residential,Thu May 15 00:00:00 EDT 2008,223000.0,38.696740,-121.350519
970,3557 SODA WAY,SACRAMENTO,95834,CA,0,0,0,Residential,Thu May 15 00:00:00 EDT 2008,224000.0,38.631026,-121.501879
971,3528 SAINT GEORGE DR,SACRAMENTO,95821,CA,3,1,1040,Residential,Thu May 15 00:00:00 EDT 2008,224000.0,38.629468,-121.376445
972,7381 WASHBURN WAY,NORTH HIGHLANDS,95660,CA,3,1,960,Residential,Thu May 15 00:00:00 EDT 2008,224252.0,38.703550,-121.375103
973,2181 WINTERHAVEN CIR,CAMERON PARK,95682,CA,3,2,0,Residential,Thu May 15 00:00:00 EDT 2008,224500.0,38.697570,-120.995739
974,7540 HICKORY AVE,ORANGEVALE,95662,CA,3,1,1456,Residential,Thu May 15 00:00:00 EDT 2008,225000.0,38.703056,-121.235221
976,2400 INVERNESS DR,LINCOLN,95648,CA,3,2,1358,Residential,Thu May 15 00:00:00 EDT 2008,229027.0,38.897814,-121.324691
977,5 BISHOPGATE CT,SACRAMENTO,95823,CA,4,2,1329,Residential,Thu May 15 00:00:00 EDT 2008,229500.0,38.467936,-121.445477
978,5601 REXLEIGH DR,SACRAMENTO,95823,CA,4,2,1715,Residential,Thu May 15 00:00:00 EDT 2008,230000.0,38.445342,-121.441504
979,1909 YARNELL WAY,ELK GROVE,95758,CA,3,2,1262,Residential,Thu May 15 00:00:00 EDT 2008,230000.0,38.417382,-121.484325
980,9169 GARLINGTON CT,SACRAMENTO,95829,CA,4,3,2280,Residential,Thu May 15 00:00:00 EDT 2008,232425.0,38.457679,-121.359620
981,6932 RUSKUT WAY,SACRAMENTO,95823,CA,3,2,1477,Residential,Thu May 15 00:00:00 EDT 2008,234000.0,38.499893,-121.458890
982,7933 DAFFODIL WAY,CITRUS HEIGHTS,95610,CA,3,2,1216,Residential,Thu May 15 00:00:00 EDT 2008,235000.0,38.708824,-121.256803
983,8304 RED FOX WAY,ELK GROVE,95758,CA,4,2,1685,Residential,Thu May 15 00:00:00 EDT 2008,235301.0,38.417000,-121.397424
984,3882 YELLOWSTONE LN,EL DORADO HILLS,95762,CA,3,2,1362,Residential,Thu May 15 00:00:00 EDT 2008,235738.0,38.655245,-121.075915

In [71]:
real_estate_na.dropna(axis=1)       # Use axis=1 for dropping columns with nan values

,city,zip,state,beds,baths,sq__ft,type,sale_date,latitude,longitude
0,SACRAMENTO,95838,CA,2,1,836,Residential,Wed May 21 00:00:00 EDT 2008,38.631913,-121.434879
1,SACRAMENTO,95823,CA,3,1,1167,Residential,Wed May 21 00:00:00 EDT 2008,38.478902,-121.431028
2,SACRAMENTO,95815,CA,2,1,796,Residential,Wed May 21 00:00:00 EDT 2008,38.618305,-121.443839
3,SACRAMENTO,95815,CA,2,1,852,Residential,Wed May 21 00:00:00 EDT 2008,38.616835,-121.439146
4,SACRAMENTO,95824,CA,2,1,797,Residential,Wed May 21 00:00:00 EDT 2008,38.519470,-121.435768
5,SACRAMENTO,95841,CA,3,1,1122,Condo,Wed May 21 00:00:00 EDT 2008,38.662595,-121.327813
6,SACRAMENTO,95842,CA,3,2,1104,Residential,Wed May 21 00:00:00 EDT 2008,38.681659,-121.351705
7,SACRAMENTO,95820,CA,3,1,1177,Residential,Wed May 21 00:00:00 EDT 2008,38.535092,-121.481367
8,RANCHO CORDOVA,95670,CA,2,2,941,Condo,Wed May 21 00:00:00 EDT 2008,38.621188,-121.270555
9,RIO LINDA,95673,CA,3,2,1146,Residential,Wed May 21 00:00:00 EDT 2008,38.700909,-121.442979
10,SACRAMENTO,95838,CA,3,2,909,Residential,Wed May 21 00:00:00 EDT 2008,38.637663,-121.451520
11,SACRAMENTO,95823,CA,3,2,1289,Residential,Wed May 21 00:00:00 EDT 2008,38.470746,-121.458918
12,SACRAMENTO,95815,CA,1,1,871,Residential,Wed May 21 00:00:00 EDT 2008,38.618698,-121.435833
13,SACRAMENTO,95822,CA,3,1,1020,Residential,Wed May 21 00:00:00 EDT 2008,38.482215,-121.492603
14,SACRAMENTO,95842,CA,2,2,1022,Residential,Wed May 21 00:00:00 EDT 2008,38.672914,-121.359340
15,SACRAMENTO,95842,CA,2,2,1134,Condo,Wed May 21 00:00:00 EDT 2008,38.700051,-121.351278
16,RIO LINDA,95673,CA,2,1,844,Residential,Wed May 21 00:00:00 EDT 2008,38.689591,-121.452239
17,CITRUS HEIGHTS,95621,CA,2,1,795,Condo,Wed May 21 00:00:00 EDT 2008,38.679776,-121.314089
18,SACRAMENTO,95833,CA,2,1,588,Residential,Wed May 21 00:00:00 EDT 2008,38.612099,-121.469095
19,RIO LINDA,95673,CA,3,2,1356,Residential,Wed May 21 00:00:00 EDT 2008,38.689999,-121.463220
20,CITRUS HEIGHTS,95621,CA,3,2,1118,Residential,Wed May 21 00:00:00 EDT 2008,38.707851,-121.320707
21,SACRAMENTO,95823,CA,4,2,1329,Residential,Wed May 21 00:00:00 EDT 2008,38.468173,-121.444071
22,NORTH HIGHLANDS,95660,CA,4,2,1240,Residential,Wed May 21 00:00:00 EDT 2008,38.702792,-121.382210
23,SACRAMENTO,95834,CA,3,2,1601,Residential,Wed May 21 00:00:00 EDT 2008,38.628631,-121.488097
24,NORTH HIGHLANDS,95660,CA,3,2,901,Residential,Wed May 21 00:00:00 EDT 2008,38.701499,-121.376220
25,ANTELOPE,95843,CA,3,2,1088,Residential,Wed May 21 00:00:00 EDT 2008,38.709740,-121.373770
26,SACRAMENTO,95820,CA,3,1,963,Residential,Wed May 21 00:00:00 EDT 2008,38.537526,-121.478315
27,SACRAMENTO,95832,CA,3,2,1119,Residential,Wed May 21 00:00:00 EDT 2008,38.476472,-121.501711
28,SACRAMENTO,95827,CA,4,2,1380,Residential,Wed May 21 00:00:00 EDT 2008,38.558423,-121.327948
29,SACRAMENTO,95828,CA,3,2,1248,Residential,Wed May 21 00:00:00 EDT 2008,38.472122,-121.404199
...,...,...,...,...,...,...,...,...,...,...
955,ROSEVILLE,95747,CA,3,2,1371,Residential,Thu May 15 00:00:00 EDT 2008,38.737882,-121.308142
956,NORTH HIGHLANDS,95660,CA,3,1,1310,Residential,Thu May 15 00:00:00 EDT 2008,38.694279,-121.373395
957,GALT,95632,CA,3,2,1262,Residential,Thu May 15 00:00:00 EDT 2008,38.259708,-121.311616
958,ELK GROVE,95624,CA,4,2,1740,Residential,Thu May 15 00:00:00 EDT 2008,38.444000,-121.370993
959,ANTELOPE,95843,CA,3,2,1517,Residential,Thu May 15 00:00:00 EDT 2008,38.722959,-121.347115
960,SACRAMENTO,95828,CA,3,2,1450,Residential,Thu May 15 00:00:00 EDT 2008,38.467836,-121.410366
961,ELK GROVE,95624,CA,3,2,1416,Residential,Thu May 15 00:00:00 EDT 2008,38.451398,-121.366614
962,SACRAMENTO,95828,CA,3,1,888,Residential,Thu May 15 00:00:00 EDT 2008,38.508217,-121.411207
963,CITRUS HEIGHTS,95610,CA,3,2,1882,Residential,Thu May 15 00:00:00 EDT 2008,38.715423,-121.246743
964,ELK GROVE,95757,CA,3,2,1302,Residential,Thu May 15 00:00:00 EDT 2008,38.390893,-121.437821
965,ELK GROVE,95758,CA,3,2,1418,Residential,Thu May 15 00:00:00 EDT 2008,38.424497,-121.426595
966,ROSEVILLE,95678,CA,3,2,0,Condo,Thu May 15 00:00:00 EDT 2008,38.793152,-121.290025
967,CARMICHAEL,95608,CA,4,2,1319,Residential,Thu May 15 00:00:00 EDT 2008,38.665104,-121.315901
968,GALT,95632,CA,4,2,1770,Residential,Thu May 15 00:00:00 EDT 2008,38.289544,-121.284607
969,SACRAMENTO,95842,CA,4,2,1627,Residential,Thu May 15 00:00:00 EDT 2008,38.696740,-121.350519
970,SACRAMENTO,95834,CA,0,0,0,Residential,Thu May 15 00:00:00 EDT 2008,38.631026,-121.501879
971,SACRAMENTO,95821,CA,3,1,1040,Residential,Thu May 15 00:00:00 EDT 2008,38.629468,-121.376445
972,NORTH HIGHLANDS,95660,CA,3,1,960,Residential,Thu May 15 00:00:00 EDT 2008,38.703550,-121.375103
973,CAMERON PARK,95682,CA,3,2,0,Residential,Thu May 15 00:00:00 EDT 2008,38.697570,-120.995739
974,ORANGEVALE,95662,CA,3,1,1456,Residential,Thu May 15 00:00:00 EDT 2008,38.703056,-121.235221
975,ELK GROVE,95757,CA,3,2,1450,Residential,Thu May 15 00:00:00 EDT 2008,38.389756,-121.446246
976,LINCOLN,95648,CA,3,2,1358,Residential,Thu May 15 00:00:00 EDT 2008,38.897814,-121.324691
977,SACRAMENTO,95823,CA,4,2,1329,Residential,Thu May 15 00:00:00 EDT 2008,38.467936,-121.445477
978,SACRAMENTO,95823,CA,4,2,1715,Residential,Thu May 15 00:00:00 EDT 2008,38.445342,-121.441504
979,ELK GROVE,95758,CA,3,2,1262,Residential,Thu May 15 00:00:00 EDT 2008,38.417382,-121.484325
980,SACRAMENTO,95829,CA,4,3,2280,Residential,Thu May 15 00:00:00 EDT 2008,38.457679,-121.359620
981,SACRAMENTO,95823,CA,3,2,1477,Residential,Thu May 15 00:00:00 EDT 2008,38.499893,-121.458890
982,CITRUS HEIGHTS,95610,CA,3,2,1216,Residential,Thu May 15 00:00:00 EDT 2008,38.708824,-121.256803
983,ELK GROVE,95758,CA,4,2,1685,Residential,Thu May 15 00:00:00 EDT 2008,38.417000,-121.397424
984,EL DORADO HILLS,95762,CA,3,2,1362,Residential,Thu May 15 00:00:00 EDT 2008,38.655245,-121.075915

In [72]:
real_estate_na.dropna(thresh=2)

,street,city,zip,state,beds,baths,sq__ft,type,sale_date,price,latitude,longitude
0,3526 HIGH ST,SACRAMENTO,95838,CA,2,1,836,Residential,Wed May 21 00:00:00 EDT 2008,59222.0,38.631913,-121.434879
1,51 OMAHA CT,SACRAMENTO,95823,CA,3,1,1167,Residential,Wed May 21 00:00:00 EDT 2008,68212.0,38.478902,-121.431028
2,2796 BRANCH ST,SACRAMENTO,95815,CA,2,1,796,Residential,Wed May 21 00:00:00 EDT 2008,NaN,38.618305,-121.443839
3,2805 JANETTE WAY,SACRAMENTO,95815,CA,2,1,852,Residential,Wed May 21 00:00:00 EDT 2008,69307.0,38.616835,-121.439146
4,6001 MCMAHON DR,SACRAMENTO,95824,CA,2,1,797,Residential,Wed May 21 00:00:00 EDT 2008,81900.0,38.519470,-121.435768
5,5828 PEPPERMILL CT,SACRAMENTO,95841,CA,3,1,1122,Condo,Wed May 21 00:00:00 EDT 2008,89921.0,38.662595,-121.327813
6,6048 OGDEN NASH WAY,SACRAMENTO,95842,CA,3,2,1104,Residential,Wed May 21 00:00:00 EDT 2008,90895.0,38.681659,-121.351705
7,2561 19TH AVE,SACRAMENTO,95820,CA,3,1,1177,Residential,Wed May 21 00:00:00 EDT 2008,91002.0,38.535092,-121.481367
8,11150 TRINITY RIVER DR Unit 114,RANCHO CORDOVA,95670,CA,2,2,941,Condo,Wed May 21 00:00:00 EDT 2008,94905.0,38.621188,-121.270555
9,7325 10TH ST,RIO LINDA,95673,CA,3,2,1146,Residential,Wed May 21 00:00:00 EDT 2008,98937.0,38.700909,-121.442979
10,645 MORRISON AVE,SACRAMENTO,95838,CA,3,2,909,Residential,Wed May 21 00:00:00 EDT 2008,100309.0,38.637663,-121.451520
11,4085 FAWN CIR,SACRAMENTO,95823,CA,3,2,1289,Residential,Wed May 21 00:00:00 EDT 2008,106250.0,38.470746,-121.458918
12,2930 LA ROSA RD,SACRAMENTO,95815,CA,1,1,871,Residential,Wed May 21 00:00:00 EDT 2008,106852.0,38.618698,-121.435833
13,2113 KIRK WAY,SACRAMENTO,95822,CA,3,1,1020,Residential,Wed May 21 00:00:00 EDT 2008,107502.0,38.482215,-121.492603
14,4533 LOCH HAVEN WAY,SACRAMENTO,95842,CA,2,2,1022,Residential,Wed May 21 00:00:00 EDT 2008,108750.0,38.672914,-121.359340
15,7340 HAMDEN PL,SACRAMENTO,95842,CA,2,2,1134,Condo,Wed May 21 00:00:00 EDT 2008,110700.0,38.700051,-121.351278
16,6715 6TH ST,RIO LINDA,95673,CA,2,1,844,Residential,Wed May 21 00:00:00 EDT 2008,113263.0,38.689591,-121.452239
17,6236 LONGFORD DR Unit 1,CITRUS HEIGHTS,95621,CA,2,1,795,Condo,Wed May 21 00:00:00 EDT 2008,116250.0,38.679776,-121.314089
18,250 PERALTA AVE,SACRAMENTO,95833,CA,2,1,588,Residential,Wed May 21 00:00:00 EDT 2008,120000.0,38.612099,-121.469095
19,113 LEEWILL AVE,RIO LINDA,95673,CA,3,2,1356,Residential,Wed May 21 00:00:00 EDT 2008,121630.0,38.689999,-121.463220
20,6118 STONEHAND AVE,CITRUS HEIGHTS,95621,CA,3,2,1118,Residential,Wed May 21 00:00:00 EDT 2008,122000.0,38.707851,-121.320707
21,4882 BANDALIN WAY,SACRAMENTO,95823,CA,4,2,1329,Residential,Wed May 21 00:00:00 EDT 2008,122682.0,38.468173,-121.444071
22,7511 OAKVALE CT,NORTH HIGHLANDS,95660,CA,4,2,1240,Residential,Wed May 21 00:00:00 EDT 2008,123000.0,38.702792,-121.382210
23,9 PASTURE CT,SACRAMENTO,95834,CA,3,2,1601,Residential,Wed May 21 00:00:00 EDT 2008,NaN,38.628631,-121.488097
24,3729 BAINBRIDGE DR,NORTH HIGHLANDS,95660,CA,3,2,901,Residential,Wed May 21 00:00:00 EDT 2008,125000.0,38.701499,-121.376220
25,3828 BLACKFOOT WAY,ANTELOPE,95843,CA,3,2,1088,Residential,Wed May 21 00:00:00 EDT 2008,126640.0,38.709740,-121.373770
26,4108 NORTON WAY,SACRAMENTO,95820,CA,3,1,963,Residential,Wed May 21 00:00:00 EDT 2008,127281.0,38.537526,-121.478315
27,1469 JANRICK AVE,SACRAMENTO,95832,CA,3,2,1119,Residential,Wed May 21 00:00:00 EDT 2008,129000.0,38.476472,-121.501711
28,9861 CULP WAY,SACRAMENTO,95827,CA,4,2,1380,Residential,Wed May 21 00:00:00 EDT 2008,131200.0,38.558423,-121.327948
29,7825 CREEK VALLEY CIR,SACRAMENTO,95828,CA,3,2,1248,Residential,Wed May 21 00:00:00 EDT 2008,132000.0,38.472122,-121.404199
...,...,...,...,...,...,...,...,...,...,...,...,...
955,2100 BEATTY WAY,ROSEVILLE,95747,CA,3,2,1371,Residential,Thu May 15 00:00:00 EDT 2008,208250.0,38.737882,-121.308142
956,6920 GILLINGHAM WAY,NORTH HIGHLANDS,95660,CA,3,1,1310,Residential,Thu May 15 00:00:00 EDT 2008,208318.0,38.694279,-121.373395
957,82 WILDFLOWER DR,GALT,95632,CA,3,2,1262,Residential,Thu May 15 00:00:00 EDT 2008,209347.0,38.259708,-121.311616
958,8652 BANTON CIR,ELK GROVE,95624,CA,4,2,1740,Residential,Thu May 15 00:00:00 EDT 2008,211500.0,38.444000,-121.370993
959,8428 MISTY PASS WAY,ANTELOPE,95843,CA,3,2,1517,Residential,Thu May 15 00:00:00 EDT 2008,212000.0,38.722959,-121.347115
960,7958 ROSEVIEW WAY,SACRAMENTO,95828,CA,3,2,1450,Residential,Thu May 15 00:00:00 EDT 2008,213000.0,38.467836,-121.410366
961,9020 LUKEN CT,ELK GROVE,95624,CA,3,2,1416,Residential,Thu May 15 00:00:00 EDT 2008,216000.0,38.451398,-121.366614
962,7809 VALLECITOS WAY,SACRAMENTO,95828,CA,3,1,888,Residential,Thu May 15 00:00:00 EDT 2008,216021.0,38.508217,-121.411207
963,8445 OLD AUBURN RD,CITRUS HEIGHTS,95610,CA,3,2,1882,Residential,Thu May 15 00:00:00 EDT 2008,219000.0,38.715423,-121.246743
964,10085 ATKINS DR,ELK GROVE,95757,CA,3,2,1302,Residential,Thu May 15 00:00:00 EDT 2008,219794.0,38.390893,-121.437821
965,9185 CERROLINDA CIR,ELK GROVE,95758,CA,3,2,1418,Residential,Thu May 15 00:00:00 EDT 2008,220000.0,38.424497,-121.426595
966,9197 CORTINA CIR,ROSEVILLE,95678,CA,3,2,0,Condo,Thu May 15 00:00:00 EDT 2008,220000.0,38.793152,-121.290025
967,5429 HESPER WAY,CARMICHAEL,95608,CA,4,2,1319,Residential,Thu May 15 00:00:00 EDT 2008,220000.0,38.665104,-121.315901
968,NaN,GALT,95632,CA,4,2,1770,Residential,Thu May 15 00:00:00 EDT 2008,NaN,38.289544,-121.284607
969,4900 ELUDE CT,SACRAMENTO,95842,CA,4,2,1627,Residential,Thu May 15 00:00:00 EDT 2008,223000.0,38.696740,-121.350519
970,3557 SODA WAY,SACRAMENTO,95834,CA,0,0,0,Residential,Thu May 15 00:00:00 EDT 2008,224000.0,38.631026,-121.501879
971,3528 SAINT GEORGE DR,SACRAMENTO,95821,CA,3,1,1040,Residential,Thu May 15 00:00:00 EDT 2008,224000.0,38.629468,-121.376445
972,7381 WASHBURN WAY,NORTH HIGHLANDS,95660,CA,3,1,960,Residential,Thu May 15 00:00:00 EDT 2008,224252.0,38.703550,-121.375103
973,2181 WINTERHAVEN CIR,CAMERON PARK,95682,CA,3,2,0,Residential,Thu May 15 00:00:00 EDT 2008,224500.0,38.697570,-120.995739
974,7540 HICKORY AVE,ORANGEVALE,95662,CA,3,1,1456,Residential,Thu May 15 00:00:00 EDT 2008,225000.0,38.703056,-121.235221
975,NaN,ELK GROVE,95757,CA,3,2,1450,Residential,Thu May 15 00:00:00 EDT 2008,228000.0,38.389756,-121.446246
976,2400 INVERNESS DR,LINCOLN,95648,CA,3,2,1358,Residential,Thu May 15 00:00:00 EDT 2008,229027.0,38.897814,-121.324691
977,5 BISHOPGATE CT,SACRAMENTO,95823,CA,4,2,1329,Residential,Thu May 15 00:00:00 EDT 2008,229500.0,38.467936,-121.445477
978,5601 REXLEIGH DR,SACRAMENTO,95823,CA,4,2,1715,Residential,Thu May 15 00:00:00 EDT 2008,230000.0,38.445342,-121.441504
979,1909 YARNELL WAY,ELK GROVE,95758,CA,3,2,1262,Residential,Thu May 15 00:00:00 EDT 2008,230000.0,38.417382,-121.484325
980,9169 GARLINGTON CT,SACRAMENTO,95829,CA,4,3,2280,Residential,Thu May 15 00:00:00 EDT 2008,232425.0,38.457679,-121.359620
981,6932 RUSKUT WAY,SACRAMENTO,95823,CA,3,2,1477,Residential,Thu May 15 00:00:00 EDT 2008,234000.0,38.499893,-121.458890
982,7933 DAFFODIL WAY,CITRUS HEIGHTS,95610,CA,3,2,1216,Residential,Thu May 15 00:00:00 EDT 2008,235000.0,38.708824,-121.256803
983,8304 RED FOX WAY,ELK GROVE,95758,CA,4,2,1685,Residential,Thu May 15 00:00:00 EDT 2008,235301.0,38.417000,-121.397424
984,3882 YELLOWSTONE LN,EL DORADO HILLS,95762,CA,3,2,1362,Residential,Thu May 15 00:00:00 EDT 2008,235738.0,38.655245,-121.075915

In [73]:
real_estate_na.fillna(value=0)

,street,city,zip,state,beds,baths,sq__ft,type,sale_date,price,latitude,longitude
0,3526 HIGH ST,SACRAMENTO,95838,CA,2,1,836,Residential,Wed May 21 00:00:00 EDT 2008,59222.0,38.631913,-121.434879
1,51 OMAHA CT,SACRAMENTO,95823,CA,3,1,1167,Residential,Wed May 21 00:00:00 EDT 2008,68212.0,38.478902,-121.431028
2,2796 BRANCH ST,SACRAMENTO,95815,CA,2,1,796,Residential,Wed May 21 00:00:00 EDT 2008,0.0,38.618305,-121.443839
3,2805 JANETTE WAY,SACRAMENTO,95815,CA,2,1,852,Residential,Wed May 21 00:00:00 EDT 2008,69307.0,38.616835,-121.439146
4,6001 MCMAHON DR,SACRAMENTO,95824,CA,2,1,797,Residential,Wed May 21 00:00:00 EDT 2008,81900.0,38.519470,-121.435768
5,5828 PEPPERMILL CT,SACRAMENTO,95841,CA,3,1,1122,Condo,Wed May 21 00:00:00 EDT 2008,89921.0,38.662595,-121.327813
6,6048 OGDEN NASH WAY,SACRAMENTO,95842,CA,3,2,1104,Residential,Wed May 21 00:00:00 EDT 2008,90895.0,38.681659,-121.351705
7,2561 19TH AVE,SACRAMENTO,95820,CA,3,1,1177,Residential,Wed May 21 00:00:00 EDT 2008,91002.0,38.535092,-121.481367
8,11150 TRINITY RIVER DR Unit 114,RANCHO CORDOVA,95670,CA,2,2,941,Condo,Wed May 21 00:00:00 EDT 2008,94905.0,38.621188,-121.270555
9,7325 10TH ST,RIO LINDA,95673,CA,3,2,1146,Residential,Wed May 21 00:00:00 EDT 2008,98937.0,38.700909,-121.442979
10,645 MORRISON AVE,SACRAMENTO,95838,CA,3,2,909,Residential,Wed May 21 00:00:00 EDT 2008,100309.0,38.637663,-121.451520
11,4085 FAWN CIR,SACRAMENTO,95823,CA,3,2,1289,Residential,Wed May 21 00:00:00 EDT 2008,106250.0,38.470746,-121.458918
12,2930 LA ROSA RD,SACRAMENTO,95815,CA,1,1,871,Residential,Wed May 21 00:00:00 EDT 2008,106852.0,38.618698,-121.435833
13,2113 KIRK WAY,SACRAMENTO,95822,CA,3,1,1020,Residential,Wed May 21 00:00:00 EDT 2008,107502.0,38.482215,-121.492603
14,4533 LOCH HAVEN WAY,SACRAMENTO,95842,CA,2,2,1022,Residential,Wed May 21 00:00:00 EDT 2008,108750.0,38.672914,-121.359340
15,7340 HAMDEN PL,SACRAMENTO,95842,CA,2,2,1134,Condo,Wed May 21 00:00:00 EDT 2008,110700.0,38.700051,-121.351278
16,6715 6TH ST,RIO LINDA,95673,CA,2,1,844,Residential,Wed May 21 00:00:00 EDT 2008,113263.0,38.689591,-121.452239
17,6236 LONGFORD DR Unit 1,CITRUS HEIGHTS,95621,CA,2,1,795,Condo,Wed May 21 00:00:00 EDT 2008,116250.0,38.679776,-121.314089
18,250 PERALTA AVE,SACRAMENTO,95833,CA,2,1,588,Residential,Wed May 21 00:00:00 EDT 2008,120000.0,38.612099,-121.469095
19,113 LEEWILL AVE,RIO LINDA,95673,CA,3,2,1356,Residential,Wed May 21 00:00:00 EDT 2008,121630.0,38.689999,-121.463220
20,6118 STONEHAND AVE,CITRUS HEIGHTS,95621,CA,3,2,1118,Residential,Wed May 21 00:00:00 EDT 2008,122000.0,38.707851,-121.320707
21,4882 BANDALIN WAY,SACRAMENTO,95823,CA,4,2,1329,Residential,Wed May 21 00:00:00 EDT 2008,122682.0,38.468173,-121.444071
22,7511 OAKVALE CT,NORTH HIGHLANDS,95660,CA,4,2,1240,Residential,Wed May 21 00:00:00 EDT 2008,123000.0,38.702792,-121.382210
23,9 PASTURE CT,SACRAMENTO,95834,CA,3,2,1601,Residential,Wed May 21 00:00:00 EDT 2008,0.0,38.628631,-121.488097
24,3729 BAINBRIDGE DR,NORTH HIGHLANDS,95660,CA,3,2,901,Residential,Wed May 21 00:00:00 EDT 2008,125000.0,38.701499,-121.376220
25,3828 BLACKFOOT WAY,ANTELOPE,95843,CA,3,2,1088,Residential,Wed May 21 00:00:00 EDT 2008,126640.0,38.709740,-121.373770
26,4108 NORTON WAY,SACRAMENTO,95820,CA,3,1,963,Residential,Wed May 21 00:00:00 EDT 2008,127281.0,38.537526,-121.478315
27,1469 JANRICK AVE,SACRAMENTO,95832,CA,3,2,1119,Residential,Wed May 21 00:00:00 EDT 2008,129000.0,38.476472,-121.501711
28,9861 CULP WAY,SACRAMENTO,95827,CA,4,2,1380,Residential,Wed May 21 00:00:00 EDT 2008,131200.0,38.558423,-121.327948
29,7825 CREEK VALLEY CIR,SACRAMENTO,95828,CA,3,2,1248,Residential,Wed May 21 00:00:00 EDT 2008,132000.0,38.472122,-121.404199
...,...,...,...,...,...,...,...,...,...,...,...,...
955,2100 BEATTY WAY,ROSEVILLE,95747,CA,3,2,1371,Residential,Thu May 15 00:00:00 EDT 2008,208250.0,38.737882,-121.308142
956,6920 GILLINGHAM WAY,NORTH HIGHLANDS,95660,CA,3,1,1310,Residential,Thu May 15 00:00:00 EDT 2008,208318.0,38.694279,-121.373395
957,82 WILDFLOWER DR,GALT,95632,CA,3,2,1262,Residential,Thu May 15 00:00:00 EDT 2008,209347.0,38.259708,-121.311616
958,8652 BANTON CIR,ELK GROVE,95624,CA,4,2,1740,Residential,Thu May 15 00:00:00 EDT 2008,211500.0,38.444000,-121.370993
959,8428 MISTY PASS WAY,ANTELOPE,95843,CA,3,2,1517,Residential,Thu May 15 00:00:00 EDT 2008,212000.0,38.722959,-121.347115
960,7958 ROSEVIEW WAY,SACRAMENTO,95828,CA,3,2,1450,Residential,Thu May 15 00:00:00 EDT 2008,213000.0,38.467836,-121.410366
961,9020 LUKEN CT,ELK GROVE,95624,CA,3,2,1416,Residential,Thu May 15 00:00:00 EDT 2008,216000.0,38.451398,-121.366614
962,7809 VALLECITOS WAY,SACRAMENTO,95828,CA,3,1,888,Residential,Thu May 15 00:00:00 EDT 2008,216021.0,38.508217,-121.411207
963,8445 OLD AUBURN RD,CITRUS HEIGHTS,95610,CA,3,2,1882,Residential,Thu May 15 00:00:00 EDT 2008,219000.0,38.715423,-121.246743
964,10085 ATKINS DR,ELK GROVE,95757,CA,3,2,1302,Residential,Thu May 15 00:00:00 EDT 2008,219794.0,38.390893,-121.437821
965,9185 CERROLINDA CIR,ELK GROVE,95758,CA,3,2,1418,Residential,Thu May 15 00:00:00 EDT 2008,220000.0,38.424497,-121.426595
966,9197 CORTINA CIR,ROSEVILLE,95678,CA,3,2,0,Condo,Thu May 15 00:00:00 EDT 2008,220000.0,38.793152,-121.290025
967,5429 HESPER WAY,CARMICHAEL,95608,CA,4,2,1319,Residential,Thu May 15 00:00:00 EDT 2008,220000.0,38.665104,-121.315901
968,0,GALT,95632,CA,4,2,1770,Residential,Thu May 15 00:00:00 EDT 2008,0.0,38.289544,-121.284607
969,4900 ELUDE CT,SACRAMENTO,95842,CA,4,2,1627,Residential,Thu May 15 00:00:00 EDT 2008,223000.0,38.696740,-121.350519
970,3557 SODA WAY,SACRAMENTO,95834,CA,0,0,0,Residential,Thu May 15 00:00:00 EDT 2008,224000.0,38.631026,-121.501879
971,3528 SAINT GEORGE DR,SACRAMENTO,95821,CA,3,1,1040,Residential,Thu May 15 00:00:00 EDT 2008,224000.0,38.629468,-121.376445
972,7381 WASHBURN WAY,NORTH HIGHLANDS,95660,CA,3,1,960,Residential,Thu May 15 00:00:00 EDT 2008,224252.0,38.703550,-121.375103
973,2181 WINTERHAVEN CIR,CAMERON PARK,95682,CA,3,2,0,Residential,Thu May 15 00:00:00 EDT 2008,224500.0,38.697570,-120.995739
974,7540 HICKORY AVE,ORANGEVALE,95662,CA,3,1,1456,Residential,Thu May 15 00:00:00 EDT 2008,225000.0,38.703056,-121.235221
975,0,ELK GROVE,95757,CA,3,2,1450,Residential,Thu May 15 00:00:00 EDT 2008,228000.0,38.389756,-121.446246
976,2400 INVERNESS DR,LINCOLN,95648,CA,3,2,1358,Residential,Thu May 15 00:00:00 EDT 2008,229027.0,38.897814,-121.324691
977,5 BISHOPGATE CT,SACRAMENTO,95823,CA,4,2,1329,Residential,Thu May 15 00:00:00 EDT 2008,229500.0,38.467936,-121.445477
978,5601 REXLEIGH DR,SACRAMENTO,95823,CA,4,2,1715,Residential,Thu May 15 00:00:00 EDT 2008,230000.0,38.445342,-121.441504
979,1909 YARNELL WAY,ELK GROVE,95758,CA,3,2,1262,Residential,Thu May 15 00:00:00 EDT 2008,230000.0,38.417382,-121.484325
980,9169 GARLINGTON CT,SACRAMENTO,95829,CA,4,3,2280,Residential,Thu May 15 00:00:00 EDT 2008,232425.0,38.457679,-121.359620
981,6932 RUSKUT WAY,SACRAMENTO,95823,CA,3,2,1477,Residential,Thu May 15 00:00:00 EDT 2008,234000.0,38.499893,-121.458890
982,7933 DAFFODIL WAY,CITRUS HEIGHTS,95610,CA,3,2,1216,Residential,Thu May 15 00:00:00 EDT 2008,235000.0,38.708824,-121.256803
983,8304 RED FOX WAY,ELK GROVE,95758,CA,4,2,1685,Residential,Thu May 15 00:00:00 EDT 2008,235301.0,38.417000,-121.397424
984,3882 YELLOWSTONE LN,EL DORADO HILLS,95762,CA,3,2,1362,Residential,Thu May 15 00:00:00 EDT 2008,235738.0,38.655245,-121.075915

In [74]:
real_estate_na['price'].fillna(value=real_estate_na['price'].mean())

0       59222.000000
1       68212.000000
2      234319.042487
3       69307.000000
4       81900.000000
5       89921.000000
6       90895.000000
7       91002.000000
8       94905.000000
9       98937.000000
10     100309.000000
11     106250.000000
12     106852.000000
13     107502.000000
14     108750.000000
15     110700.000000
16     113263.000000
17     116250.000000
18     120000.000000
19     121630.000000
20     122000.000000
21     122682.000000
22     123000.000000
23     234319.042487
24     125000.000000
25     126640.000000
26     127281.000000
27     129000.000000
28     131200.000000
29     132000.000000
           ...
955    208250.000000
956    208318.000000
957    209347.000000
958    211500.000000
959    212000.000000
960    213000.000000
961    216000.000000
962    216021.000000
963    219000.000000
964    219794.000000
965    220000.000000
966    220000.000000
967    220000.000000
968    234319.042487
969    223000.000000
970    224000.000000
971    224000.000000
972    224252.000000
973    224500.000000
974    225000.000000
975    228000.000000
976    229027.000000
977    229500.000000
978    230000.000000
979    230000.000000
980    232425.000000
981    234000.000000
982    235000.000000
983    235301.000000
984    235738.000000
Name: price, Length: 985, dtype: float64

# Part 4

# Groupby

The groupby method is used to group rows together and perform aggregate functions

In [3]:
import pandas as pd

In [4]:
dataframe = pd.read_csv('real-estate.csv')

In [5]:
dataframe.head()

,street,city,zip,state,beds,baths,sq__ft,type,sale_date,price,latitude,longitude
0,3526 HIGH ST,SACRAMENTO,95838,CA,2,1,836,Residential,Wed May 21 00:00:00 EDT 2008,59222,38.631913,-121.434879
1,51 OMAHA CT,SACRAMENTO,95823,CA,3,1,1167,Residential,Wed May 21 00:00:00 EDT 2008,68212,38.478902,-121.431028
2,2796 BRANCH ST,SACRAMENTO,95815,CA,2,1,796,Residential,Wed May 21 00:00:00 EDT 2008,68880,38.618305,-121.443839
3,2805 JANETTE WAY,SACRAMENTO,95815,CA,2,1,852,Residential,Wed May 21 00:00:00 EDT 2008,69307,38.616835,-121.439146
4,6001 MCMAHON DR,SACRAMENTO,95824,CA,2,1,797,Residential,Wed May 21 00:00:00 EDT 2008,81900,38.519470,-121.435768

**We can now use the .groupby() method to group rows together based on a column name. For example let's group based on city. This will create a DataFrameGroupBy object:**

In [7]:
dataframe.groupby('city')

This object can be saved as a variable

In [8]:
city_grouped = dataframe.groupby("city")

Now we can aggregate using the variable

In [9]:
city_grouped.mean()

,zip,beds,baths,sq__ft,price,latitude,longitude
city,,,,,,,
ANTELOPE,95843.000000,3.363636,2.212121,1716.636364,232496.393939,38.714018,-121.362247
AUBURN,95603.000000,3.000000,2.600000,898.600000,405890.800000,38.912847,-121.082133
CAMERON PARK,95682.000000,2.444444,1.666667,224.000000,267944.444444,38.685578,-120.998527
CARMICHAEL,95608.000000,3.050000,1.850000,1553.100000,295684.750000,38.640161,-121.325816
CITRUS HEIGHTS,95618.800000,3.228571,1.914286,1308.685714,187114.914286,38.701383,-121.300204
COOL,95614.000000,3.000000,2.000000,1457.000000,300000.000000,38.905927,-120.975169
DIAMOND SPRINGS,95619.000000,3.000000,2.000000,1300.000000,216033.000000,38.688255,-120.810235
EL DORADO,95623.000000,2.500000,1.500000,1332.000000,247000.000000,38.676022,-120.861647
EL DORADO HILLS,95762.000000,3.434783,2.304348,233.434783,491698.956522,38.672475,-121.055980
ELK GROVE,95717.719298,3.359649,2.157895,1848.728070,271157.692982,38.414923,-121.415423
ELVERTA,95626.000000,3.250000,2.000000,1241.500000,132866.000000,38.713911,-121.416466
FAIR OAKS,95628.000000,3.000000,2.000000,1659.777778,303500.666667,38.660517,-121.258199
FOLSOM,95630.000000,3.294118,2.117647,1948.411765,414960.176471,38.670713,-121.139698
FORESTHILL,95631.000000,0.000000,0.000000,0.000000,194818.000000,39.020808,-120.821518
GALT,95632.000000,3.333333,2.000000,1560.857143,236943.428571,38.270887,-121.299923
GARDEN VALLEY,95633.000000,3.000000,2.000000,0.000000,490000.000000,38.842550,-120.875400
GOLD RIVER,95670.000000,2.250000,1.500000,1634.500000,358000.000000,38.628003,-121.258031
GRANITE BAY,95746.000000,4.666667,3.000000,2974.000000,678733.333333,38.745025,-121.193948
GREENWOOD,95635.000000,3.000000,2.000000,2846.000000,395000.000000,38.945357,-120.908822
LINCOLN,95648.000000,1.000000,0.680556,133.875000,96539.263889,38.880325,-121.290704
LOOMIS,95650.000000,4.000000,3.000000,1476.000000,567000.000000,38.819216,-121.165890
MATHER,95655.000000,3.000000,2.000000,2093.000000,237800.000000,38.547991,-121.280483
MEADOW VISTA,95722.000000,3.000000,1.000000,1216.000000,230000.000000,39.008159,-121.036230
NORTH HIGHLANDS,95660.000000,3.047619,1.571429,1150.333333,135659.333333,38.682600,-121.375698
ORANGEVALE,95662.000000,3.363636,2.000000,1647.363636,279159.545455,38.684370,-121.226420
PENRYN,95663.000000,3.000000,2.000000,1320.000000,506688.000000,38.862708,-121.162092
PLACERVILLE,95667.000000,2.900000,1.900000,852.600000,363863.400000,38.740994,-120.806783
POLLOCK PINES,95726.000000,2.666667,1.666667,1328.000000,240302.666667,38.746025,-120.602077
RANCHO CORDOVA,95698.285714,2.642857,1.714286,1362.071429,263405.928571,38.574148,-121.267942
RANCHO MURIETA,95683.000000,2.666667,1.666667,1975.333333,297750.000000,38.497430,-121.087465
RIO LINDA,95673.000000,2.692308,1.538462,1121.153846,172727.615385,38.691752,-121.452448
ROCKLIN,95733.941176,2.764706,1.764706,878.647059,381835.823529,38.803461,-121.251611
ROSEVILLE,95703.916667,2.770833,1.770833,1028.687500,324528.250000,38.765397,-121.304739
SACRAMENTO,95828.412301,3.027335,1.760820,1394.259681,197735.988610,38.562167,-121.443059
SHINGLE SPRINGS,95682.000000,0.000000,0.000000,0.000000,275000.000000,38.643470,-120.888183
SLOUGHHOUSE,95683.000000,3.000000,4.000000,5822.000000,2000.000000,38.490447,-121.129337
WALNUT GROVE,95690.000000,3.000000,1.000000,1727.000000,380000.000000,38.247659,-121.515129
WEST SACRAMENTO,95691.000000,0.666667,0.333333,294.666667,170700.000000,38.572518,-121.532576
WILTON,95693.000000,3.400000,2.000000,2807.800000,617508.400000,38.401021,-121.210017

#### Or we can call the groupby function for each aggregation

Some more examples

In [10]:
city_grouped.std()

,zip,beds,baths,sq__ft,price,latitude,longitude
city,,,,,,,
ANTELOPE,0.000000,0.783349,0.484612,574.401799,71963.663914,0.007230,0.017789
AUBURN,0.000000,1.000000,0.547723,955.052250,131800.852134,0.032790,0.017202
CAMERON PARK,0.000000,1.130388,0.707107,672.000000,115064.776443,0.011584,0.004400
CARMICHAEL,0.000000,0.686333,0.489360,563.188096,142134.046072,0.021218,0.014140
CITRUS HEIGHTS,4.464237,0.689660,0.612201,281.888669,58423.361610,0.015006,0.020861
COOL,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DIAMOND SPRINGS,NaN,NaN,NaN,NaN,NaN,NaN,NaN
EL DORADO,0.000000,0.707107,0.707107,412.950360,59396.969620,0.003870,0.024790
EL DORADO HILLS,0.000000,1.561645,1.184551,629.075716,162001.012744,0.017748,0.019844
ELK GROVE,61.368683,1.234656,0.782315,865.206193,91511.950277,0.022146,0.035255
ELVERTA,0.000000,0.500000,0.000000,168.264672,7538.887451,0.005909,0.015239
FAIR OAKS,0.000000,0.866025,1.224745,797.931040,180415.727631,0.008703,0.022330
FOLSOM,0.000000,1.403776,0.927520,958.790909,129612.259950,0.017263,0.031034
FORESTHILL,NaN,NaN,NaN,NaN,NaN,NaN,NaN
GALT,0.000000,0.966092,0.774597,712.780211,87325.298611,0.015581,0.010352
GARDEN VALLEY,NaN,NaN,NaN,NaN,NaN,NaN,NaN
GOLD RIVER,0.000000,1.707825,1.000000,1261.185818,113363.721416,0.001830,0.006034
GRANITE BAY,0.000000,0.577350,0.000000,660.463474,80030.077679,0.030105,0.040968
GREENWOOD,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LINCOLN,0.000000,1.652996,1.111101,463.592066,147978.894155,0.012646,0.014451
LOOMIS,0.000000,0.000000,1.414214,209.303607,384666.088965,0.008315,0.046021
MATHER,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MEADOW VISTA,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NORTH HIGHLANDS,0.000000,0.497613,0.507093,176.899501,34661.371840,0.017050,0.003779
ORANGEVALE,0.000000,0.674200,0.774597,523.986311,82732.459786,0.015687,0.019664
PENRYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PLACERVILLE,0.000000,1.197219,0.875595,970.931306,145898.109463,0.037041,0.060062
POLLOCK PINES,0.000000,0.577350,0.577350,48.497423,57110.374026,0.034163,0.003903
RANCHO CORDOVA,35.809017,1.768328,1.242970,1086.610017,99845.317005,0.029914,0.034797
RANCHO MURIETA,0.000000,2.309401,1.527525,1725.948242,175335.571120,0.013365,0.012453
RIO LINDA,0.000000,1.031553,0.660225,398.183133,76711.755986,0.006572,0.009451
ROCKLIN,43.348112,1.751050,1.091410,1010.539704,110976.438802,0.019943,0.031637
ROSEVILLE,37.271764,1.490960,0.994444,1045.069114,134714.710494,0.025483,0.039746
SACRAMENTO,8.303376,1.026667,0.727613,600.840269,100870.200819,0.078120,0.057484
SHINGLE SPRINGS,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SLOUGHHOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
WALNUT GROVE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
WEST SACRAMENTO,0.000000,1.154701,0.577350,510.377638,27004.999537,0.010950,0.004389
WILTON,0.000000,2.073644,1.224745,1784.476170,188411.185096,0.028333,0.023032

In [17]:
dataframe[dataframe['city']=='ANTELOPE'].sort_values(by='sq__ft',ascending=False)

,street,city,zip,state,beds,baths,sq__ft,type,sale_date,price,latitude,longitude
792,7921 DOE TRAIL WAY,ANTELOPE,95843,CA,5,3,3134,Residential,Fri May 16 00:00:00 EDT 2008,315000,38.711927,-121.343608
811,4509 WINJE DR,ANTELOPE,95843,CA,3,2,2960,Residential,Fri May 16 00:00:00 EDT 2008,350000,38.709513,-121.359357
455,3305 RIO ROCA CT,ANTELOPE,95843,CA,4,3,2652,Residential,Mon May 19 00:00:00 EDT 2008,239700,38.725079,-121.387698
736,4240 WINJE DR,ANTELOPE,95843,CA,4,2,2504,Residential,Fri May 16 00:00:00 EDT 2008,246750,38.708840,-121.359559
500,4741 PACIFIC PARK DR,ANTELOPE,95843,CA,5,3,2347,Residential,Mon May 19 00:00:00 EDT 2008,325000,38.709299,-121.353056
499,4712 PISMO BEACH DR,ANTELOPE,95843,CA,5,3,2346,Residential,Mon May 19 00:00:00 EDT 2008,320000,38.707705,-121.354153
769,4636 TEAL BAY CT,ANTELOPE,95843,CA,4,2,2160,Residential,Fri May 16 00:00:00 EDT 2008,290000,38.704554,-121.354753
525,3361 ALDER CANYON WAY,ANTELOPE,95843,CA,4,3,2085,Residential,Mon May 19 00:00:00 EDT 2008,408431,38.727649,-121.385656
444,4508 OLD DAIRY DR,ANTELOPE,95843,CA,4,3,2026,Residential,Mon May 19 00:00:00 EDT 2008,231200,38.722860,-121.358939
700,7901 GAZELLE TRAIL WAY,ANTELOPE,95843,CA,4,2,1953,Residential,Fri May 16 00:00:00 EDT 2008,207744,38.711740,-121.342675
729,4085 COUNTRY DR,ANTELOPE,95843,CA,4,3,1915,Residential,Fri May 16 00:00:00 EDT 2008,240000,38.706209,-121.369509
466,5308 MARBURY WAY,ANTELOPE,95843,CA,3,2,1830,Residential,Mon May 19 00:00:00 EDT 2008,254172,38.710221,-121.341707
139,7837 ABBINGTON WAY,ANTELOPE,95843,CA,4,2,1830,Residential,Wed May 21 00:00:00 EDT 2008,387731,38.709873,-121.339472
264,8108 FILIFERA WAY,ANTELOPE,95843,CA,4,3,1768,Residential,Tue May 20 00:00:00 EDT 2008,265000,38.717042,-121.354680
650,3536 SUN MAIDEN WAY,ANTELOPE,95843,CA,3,2,1711,Residential,Fri May 16 00:00:00 EDT 2008,161500,38.709680,-121.382328
910,8636 LONGSPUR WAY,ANTELOPE,95843,CA,3,2,1670,Residential,Thu May 15 00:00:00 EDT 2008,157296,38.725873,-121.358560
658,4008 GREY LIVERY WAY,ANTELOPE,95843,CA,3,2,1669,Residential,Fri May 16 00:00:00 EDT 2008,168750,38.718460,-121.370862
257,5312 MARBURY WAY,ANTELOPE,95843,CA,3,2,1574,Residential,Tue May 20 00:00:00 EDT 2008,255000,38.710221,-121.341651
261,5712 MELBURY CIR,ANTELOPE,95843,CA,3,2,1567,Residential,Tue May 20 00:00:00 EDT 2008,261000,38.705849,-121.334701
959,8428 MISTY PASS WAY,ANTELOPE,95843,CA,3,2,1517,Residential,Thu May 15 00:00:00 EDT 2008,212000,38.722959,-121.347115
696,8716 LONGSPUR WAY,ANTELOPE,95843,CA,3,2,1479,Residential,Fri May 16 00:00:00 EDT 2008,205000,38.724083,-121.358400
222,4437 MITCHUM CT,ANTELOPE,95843,CA,3,2,1393,Residential,Tue May 20 00:00:00 EDT 2008,200000,38.704407,-121.361130
208,3228 BAGGAN CT,ANTELOPE,95843,CA,3,2,1392,Residential,Tue May 20 00:00:00 EDT 2008,165000,38.715346,-121.388163
67,7895 CABER WAY,ANTELOPE,95843,CA,3,2,1362,Residential,Wed May 21 00:00:00 EDT 2008,194818,38.711279,-121.393449
735,8316 NORTHAM DR,ANTELOPE,95843,CA,3,2,1235,Residential,Fri May 16 00:00:00 EDT 2008,246544,38.720767,-121.376678
60,4844 CLYDEBANK WAY,ANTELOPE,95843,CA,3,2,1215,Residential,Wed May 21 00:00:00 EDT 2008,182716,38.714609,-121.347887
902,3604 KODIAK WAY,ANTELOPE,95843,CA,3,2,1206,Residential,Thu May 15 00:00:00 EDT 2008,142000,38.706175,-121.379776
448,8721 SPRUCE RIDGE WAY,ANTELOPE,95843,CA,3,2,1187,Residential,Mon May 19 00:00:00 EDT 2008,234000,38.727657,-121.391028
25,3828 BLACKFOOT WAY,ANTELOPE,95843,CA,3,2,1088,Residential,Wed May 21 00:00:00 EDT 2008,126640,38.709740,-121.373770
43,5708 RIDGEPOINT DR,ANTELOPE,95843,CA,2,2,1043,Residential,Wed May 21 00:00:00 EDT 2008,161250,38.720270,-121.331555
214,7863 CRESTLEIGH CT,ANTELOPE,95843,CA,2,2,1007,Residential,Tue May 20 00:00:00 EDT 2008,180000,38.710889,-121.358876
438,3318 DAVIDSON DR,ANTELOPE,95843,CA,3,1,988,Residential,Mon May 19 00:00:00 EDT 2008,223139,38.705753,-121.388917
362,8020 WALERGA RD,ANTELOPE,95843,CA,2,2,836,Condo,Mon May 19 00:00:00 EDT 2008,115000,38.716070,-121.364468

In [15]:
city_grouped.min()

,street,zip,state,beds,baths,sq__ft,type,sale_date,price,latitude,longitude
city,,,,,,,,,,,
ANTELOPE,3228 BAGGAN CT,95843,CA,2,1,836,Condo,Fri May 16 00:00:00 EDT 2008,115000,38.704407,-121.393449
AUBURN,1484 RADCLIFFE WAY,95603,CA,2,2,0,Condo,Fri May 16 00:00:00 EDT 2008,260000,38.865246,-121.097862
CAMERON PARK,2181 WINTERHAVEN CIR,95682,CA,0,0,0,Condo,Fri May 16 00:00:00 EDT 2008,119000,38.664225,-121.007173
CARMICHAEL,2109 HAMLET PL,95608,CA,2,1,936,Condo,Fri May 16 00:00:00 EDT 2008,139500,38.602461,-121.353639
CITRUS HEIGHTS,5448 MAIDSTONE WAY,95610,CA,2,1,795,Condo,Fri May 16 00:00:00 EDT 2008,30000,38.665395,-121.328555
COOL,2341 BIG STRIKE TRL,95614,CA,3,2,1457,Residential,Fri May 16 00:00:00 EDT 2008,300000,38.905927,-120.975169
DIAMOND SPRINGS,636 CRESTVIEW DR,95619,CA,3,2,1300,Residential,Fri May 16 00:00:00 EDT 2008,216033,38.688255,-120.810235
EL DORADO,4885 SUMMIT VIEW DR,95623,CA,2,1,1040,Residential,Fri May 16 00:00:00 EDT 2008,205000,38.673285,-120.879176
EL DORADO HILLS,1032 SOUZA DR,95762,CA,0,0,0,Residential,Fri May 16 00:00:00 EDT 2008,235738,38.628459,-121.081752
ELK GROVE,10085 ATKINS DR,95624,CA,0,0,0,Condo,Fri May 16 00:00:00 EDT 2008,71000,38.305200,-121.484325
ELVERTA,2421 SANTINA WAY,95626,CA,3,2,1080,Residential,Mon May 19 00:00:00 EDT 2008,126000,38.705834,-121.439190
FAIR OAKS,4128 HILL ST,95628,CA,2,1,960,Condo,Fri May 16 00:00:00 EDT 2008,142500,38.641670,-121.303675
FOLSOM,100 CHELSEA CT,95630,CA,0,0,0,Condo,Fri May 16 00:00:00 EDT 2008,200000,38.645700,-121.187100
FORESTHILL,5890 TT TRAK,95631,CA,0,0,0,Residential,Fri May 16 00:00:00 EDT 2008,194818,39.020808,-120.821518
GALT,1033 PARK STREAM DR,95632,CA,0,0,0,Residential,Fri May 16 00:00:00 EDT 2008,106716,38.241514,-121.321266
GARDEN VALLEY,6401 MARSHALL RD,95633,CA,3,2,0,Residential,Fri May 16 00:00:00 EDT 2008,490000,38.842550,-120.875400
GOLD RIVER,11281 STANFORD COURT LN Unit 604,95670,CA,0,0,0,Condo,Mon May 19 00:00:00 EDT 2008,299000,38.625289,-121.261669
GRANITE BAY,4629 DORCHESTER LN,95746,CA,4,3,2356,Residential,Fri May 16 00:00:00 EDT 2008,600000,38.723545,-121.219142
GREENWOOD,1693 SHELTER COVE DR,95635,CA,3,2,2846,Residential,Wed May 21 00:00:00 EDT 2008,395000,38.945357,-120.908822
LINCOLN,100 CRYSTALWOOD CIR,95648,CA,0,0,0,Condo,Fri May 16 00:00:00 EDT 2008,1551,38.844116,-121.324691
LOOMIS,3935 EL MONTE DR,95650,CA,4,2,1328,Residential,Fri May 16 00:00:00 EDT 2008,295000,38.813337,-121.198432
MATHER,4243 MIDDLEBURY WAY,95655,CA,3,2,2093,Residential,Wed May 21 00:00:00 EDT 2008,237800,38.547991,-121.280483
MEADOW VISTA,2284 LOS ROBLES RD,95722,CA,3,1,1216,Residential,Tue May 20 00:00:00 EDT 2008,230000,39.008159,-121.036230
NORTH HIGHLANDS,3692 PAYNE WAY,95660,CA,2,1,888,Residential,Fri May 16 00:00:00 EDT 2008,63000,38.650445,-121.382210
ORANGEVALE,5544 CAMAS CT,95662,CA,2,1,1176,Residential,Fri May 16 00:00:00 EDT 2008,183200,38.664186,-121.254319
PENRYN,1500 ORANGE HILL LN,95663,CA,3,2,1320,Residential,Mon May 19 00:00:00 EDT 2008,506688,38.862708,-121.162092
PLACERVILLE,1230 SANDRA CIR,95667,CA,0,0,0,Residential,Fri May 16 00:00:00 EDT 2008,205000,38.690867,-120.910963
POLLOCK PINES,2250 FOREBAY RD,95726,CA,2,1,1284,Residential,Fri May 16 00:00:00 EDT 2008,175000,38.708315,-120.604760
RANCHO CORDOVA,10245 LOS PALOS DR,95670,CA,0,0,0,Condo,Fri May 16 00:00:00 EDT 2008,94905,38.527384,-121.318669
RANCHO MURIETA,14788 NATCHEZ CT,95683,CA,0,0,0,Residential,Tue May 20 00:00:00 EDT 2008,97750,38.487400,-121.100032
RIO LINDA,1028 FALLON PLACE CT,95673,CA,0,0,0,Residential,Fri May 16 00:00:00 EDT 2008,30000,38.682790,-121.463933
ROCKLIN,2121 HANNAH WAY,95677,CA,0,0,0,Residential,Fri May 16 00:00:00 EDT 2008,230095,38.772672,-121.293609
ROSEVILLE,10001 WOODCREEK OAKS BLVD Unit 1415,95661,CA,0,0,0,Condo,Fri May 16 00:00:00 EDT 2008,115000,38.724460,-121.378718
SACRAMENTO,1 KENNELFORD CIR,95811,CA,0,0,0,Condo,Fri May 16 00:00:00 EDT 2008,40000,38.440040,-121.551704
SHINGLE SPRINGS,6007 MARYBELLE LN,95682,CA,0,0,0,Unkown,Fri May 16 00:00:00 EDT 2008,275000,38.643470,-120.888183
SLOUGHHOUSE,14151 INDIO DR,95683,CA,3,4,5822,Residential,Fri May 16 00:00:00 EDT 2008,2000,38.490447,-121.129337
WALNUT GROVE,14004 WALNUT AVE,95690,CA,3,1,1727,Residential,Fri May 16 00:00:00 EDT 2008,380000,38.247659,-121.515129
WEST SACRAMENTO,1525 PENNSYLVANIA AVE,95691,CA,0,0,0,Residential,Thu May 15 00:00:00 EDT 2008,147000,38.563084,-121.535579
WILTON,11215 SHARRMONT CT,95693,CA,0,0,0,Residential,Fri May 16 00:00:00 EDT 2008,372000,38.350620,-121.240628

In [10]:
city_grouped.max()

,street,zip,state,beds,baths,sq__ft,type,sale_date,price,latitude,longitude
city,,,,,,,,,,,
ANTELOPE,8721 SPRUCE RIDGE WAY,95843,CA,5,3,3134,Residential,Wed May 21 00:00:00 EDT 2008,408431,38.727657,-121.331555
AUBURN,820 DANA CT,95603,CA,4,3,2278,Residential,Tue May 20 00:00:00 EDT 2008,560000,38.939802,-121.054575
CAMERON PARK,3429 FERNBROOK CT,95682,CA,4,2,2016,Residential,Tue May 20 00:00:00 EDT 2008,425000,38.697570,-120.994949
CARMICHAEL,7110 STELLA LN Unit 15,95608,CA,4,3,3357,Residential,Wed May 21 00:00:00 EDT 2008,668365,38.671995,-121.300055
CITRUS HEIGHTS,8445 OLD AUBURN RD,95621,CA,5,4,2085,Residential,Wed May 21 00:00:00 EDT 2008,305000,38.720868,-121.246743
COOL,2341 BIG STRIKE TRL,95614,CA,3,2,1457,Residential,Fri May 16 00:00:00 EDT 2008,300000,38.905927,-120.975169
DIAMOND SPRINGS,636 CRESTVIEW DR,95619,CA,3,2,1300,Residential,Fri May 16 00:00:00 EDT 2008,216033,38.688255,-120.810235
EL DORADO,6320 EL DORADO ST,95623,CA,3,2,1624,Residential,Mon May 19 00:00:00 EDT 2008,289000,38.678758,-120.844118
EL DORADO HILLS,955 BIG SUR CT,95762,CA,6,5,2199,Residential,Wed May 21 00:00:00 EDT 2008,879000,38.706692,-121.015862
ELK GROVE,9967 HATHERTON WAY,95758,CA,6,4,4303,Residential,Wed May 21 00:00:00 EDT 2008,510000,38.452075,-121.335541
ELVERTA,7944 DOMINION WAY,95626,CA,4,2,1416,Residential,Wed May 21 00:00:00 EDT 2008,140000,38.718650,-121.407684
FAIR OAKS,8806 PHOENIX AVE,95628,CA,5,5,3173,Residential,Tue May 20 00:00:00 EDT 2008,680000,38.667450,-121.230101
FOLSOM,868 HILDEBRAND CIR,95630,CA,5,3,3261,Residential,Wed May 21 00:00:00 EDT 2008,636000,38.703962,-121.090178
FORESTHILL,5890 TT TRAK,95631,CA,0,0,0,Residential,Fri May 16 00:00:00 EDT 2008,194818,39.020808,-120.821518
GALT,993 MANTON CT,95632,CA,5,4,3746,Residential,Wed May 21 00:00:00 EDT 2008,420000,38.290119,-121.284607
GARDEN VALLEY,6401 MARSHALL RD,95633,CA,3,2,0,Residential,Fri May 16 00:00:00 EDT 2008,490000,38.842550,-120.875400
GOLD RIVER,2049 EMPIRE MINE CIR,95670,CA,4,2,3037,Residential,Wed May 21 00:00:00 EDT 2008,528000,38.629299,-121.249021
GRANITE BAY,6222 CALLE MONTALVO CIR,95746,CA,5,3,3670,Residential,Mon May 19 00:00:00 EDT 2008,760000,38.779435,-121.146676
GREENWOOD,1693 SHELTER COVE DR,95635,CA,3,2,2846,Residential,Wed May 21 00:00:00 EDT 2008,395000,38.945357,-120.908822
LINCOLN,96 CRYSTALWOOD CIR,95648,CA,5,4,2457,Residential,Tue May 20 00:00:00 EDT 2008,512000,38.904869,-121.231742
LOOMIS,5747 KING RD,95650,CA,4,4,1624,Residential,Tue May 20 00:00:00 EDT 2008,839000,38.825096,-121.133348
MATHER,4243 MIDDLEBURY WAY,95655,CA,3,2,2093,Residential,Wed May 21 00:00:00 EDT 2008,237800,38.547991,-121.280483
MEADOW VISTA,2284 LOS ROBLES RD,95722,CA,3,1,1216,Residential,Tue May 20 00:00:00 EDT 2008,230000,39.008159,-121.036230
NORTH HIGHLANDS,7511 OAKVALE CT,95660,CA,4,2,1587,Residential,Wed May 21 00:00:00 EDT 2008,224252,38.703550,-121.367497
ORANGEVALE,9021 MADISON AVE,95662,CA,4,4,3056,Residential,Wed May 21 00:00:00 EDT 2008,475000,38.711470,-121.192316
PENRYN,1500 ORANGE HILL LN,95663,CA,3,2,1320,Residential,Mon May 19 00:00:00 EDT 2008,506688,38.862708,-121.162092
PLACERVILLE,9970 STATE HIGHWAY 193,95667,CA,4,3,2295,Residential,Tue May 20 00:00:00 EDT 2008,677048,38.813546,-120.693641
POLLOCK PINES,5615 LUPIN LN,95726,CA,3,2,1380,Residential,Wed May 21 00:00:00 EDT 2008,280908,38.774910,-120.597599
RANCHO CORDOVA,5420 ALMOND FALLS WAY,95742,CA,5,4,3615,Residential,Wed May 21 00:00:00 EDT 2008,430000,38.625932,-121.217611
RANCHO MURIETA,6306 CONEJO,95683,CA,4,3,3192,Residential,Wed May 21 00:00:00 EDT 2008,425000,38.512602,-121.075129
RIO LINDA,77 RINETTI WAY,95673,CA,4,2,1690,Residential,Wed May 21 00:00:00 EDT 2008,300000,38.702893,-121.435204
ROCKLIN,6288 LONETREE BLVD,95765,CA,5,3,2607,Residential,Tue May 20 00:00:00 EDT 2008,600000,38.837455,-121.203600
ROSEVILLE,9197 CORTINA CIR,95747,CA,5,3,3838,Residential,Tue May 20 00:00:00 EDT 2008,614000,38.808581,-121.226494
SACRAMENTO,9937 BURLINE ST,95864,CA,8,4,4246,Residential,Wed May 21 00:00:00 EDT 2008,699000,38.700051,-121.309243
SHINGLE SPRINGS,6007 MARYBELLE LN,95682,CA,0,0,0,Unkown,Fri May 16 00:00:00 EDT 2008,275000,38.643470,-120.888183
SLOUGHHOUSE,14151 INDIO DR,95683,CA,3,4,5822,Residential,Fri May 16 00:00:00 EDT 2008,2000,38.490447,-121.129337
WALNUT GROVE,14004 WALNUT AVE,95690,CA,3,1,1727,Residential,Fri May 16 00:00:00 EDT 2008,380000,38.247659,-121.515129
WEST SACRAMENTO,612 STONE BLVD,95691,CA,2,1,884,Residential,Thu May 15 00:00:00 EDT 2008,200100,38.584526,-121.527539
WILTON,9741 SADDLEBRED CT,95693,CA,5,3,4400,Residential,Wed May 21 00:00:00 EDT 2008,884790,38.416809,-121.188211

In [15]:
city_grouped.count().sort_values(by='sq__ft',ascending=False)

,street,zip,state,beds,baths,sq__ft,type,sale_date,price,latitude,longitude
city,,,,,,,,,,,
SACRAMENTO,439,439,439,439,439,439,439,439,439,439,439
ELK GROVE,114,114,114,114,114,114,114,114,114,114,114
LINCOLN,72,72,72,72,72,72,72,72,72,72,72
ROSEVILLE,48,48,48,48,48,48,48,48,48,48,48
CITRUS HEIGHTS,35,35,35,35,35,35,35,35,35,35,35
ANTELOPE,33,33,33,33,33,33,33,33,33,33,33
RANCHO CORDOVA,28,28,28,28,28,28,28,28,28,28,28
EL DORADO HILLS,23,23,23,23,23,23,23,23,23,23,23
GALT,21,21,21,21,21,21,21,21,21,21,21
NORTH HIGHLANDS,21,21,21,21,21,21,21,21,21,21,21
CARMICHAEL,20,20,20,20,20,20,20,20,20,20,20
FOLSOM,17,17,17,17,17,17,17,17,17,17,17
ROCKLIN,17,17,17,17,17,17,17,17,17,17,17
RIO LINDA,13,13,13,13,13,13,13,13,13,13,13
ORANGEVALE,11,11,11,11,11,11,11,11,11,11,11
PLACERVILLE,10,10,10,10,10,10,10,10,10,10,10
FAIR OAKS,9,9,9,9,9,9,9,9,9,9,9
CAMERON PARK,9,9,9,9,9,9,9,9,9,9,9
AUBURN,5,5,5,5,5,5,5,5,5,5,5
WILTON,5,5,5,5,5,5,5,5,5,5,5
GOLD RIVER,4,4,4,4,4,4,4,4,4,4,4
ELVERTA,4,4,4,4,4,4,4,4,4,4,4
GRANITE BAY,3,3,3,3,3,3,3,3,3,3,3
POLLOCK PINES,3,3,3,3,3,3,3,3,3,3,3
WEST SACRAMENTO,3,3,3,3,3,3,3,3,3,3,3
RANCHO MURIETA,3,3,3,3,3,3,3,3,3,3,3
LOOMIS,2,2,2,2,2,2,2,2,2,2,2
EL DORADO,2,2,2,2,2,2,2,2,2,2,2
SLOUGHHOUSE,1,1,1,1,1,1,1,1,1,1,1
WALNUT GROVE,1,1,1,1,1,1,1,1,1,1,1
SHINGLE SPRINGS,1,1,1,1,1,1,1,1,1,1,1
DIAMOND SPRINGS,1,1,1,1,1,1,1,1,1,1,1
PENRYN,1,1,1,1,1,1,1,1,1,1,1
MATHER,1,1,1,1,1,1,1,1,1,1,1
GREENWOOD,1,1,1,1,1,1,1,1,1,1,1
GARDEN VALLEY,1,1,1,1,1,1,1,1,1,1,1
FORESTHILL,1,1,1,1,1,1,1,1,1,1,1
COOL,1,1,1,1,1,1,1,1,1,1,1
MEADOW VISTA,1,1,1,1,1,1,1,1,1,1,1

In [16]:
city_grouped.describe()

                   zip                                                      \
                 count          mean        std      min      25%      50%
city
ANTELOPE          33.0  95843.000000   0.000000  95843.0  95843.0  95843.0
AUBURN             5.0  95603.000000   0.000000  95603.0  95603.0  95603.0
CAMERON PARK       9.0  95682.000000   0.000000  95682.0  95682.0  95682.0
CARMICHAEL        20.0  95608.000000   0.000000  95608.0  95608.0  95608.0
CITRUS HEIGHTS    35.0  95618.800000   4.464237  95610.0  95621.0  95621.0
COOL               1.0  95614.000000        NaN  95614.0  95614.0  95614.0
DIAMOND SPRINGS    1.0  95619.000000        NaN  95619.0  95619.0  95619.0
EL DORADO          2.0  95623.000000   0.000000  95623.0  95623.0  95623.0
EL DORADO HILLS   23.0  95762.000000   0.000000  95762.0  95762.0  95762.0
ELK GROVE        114.0  95717.719298  61.368683  95624.0  95624.0  95757.0
ELVERTA            4.0  95626.000000   0.000000  95626.0  95626.0  95626.0
FAIR OAKS          9.0  95628.000000   0.000000  95628.0  95628.0  95628.0
FOLSOM            17.0  95630.000000   0.000000  95630.0  95630.0  95630.0
FORESTHILL         1.0  95631.000000        NaN  95631.0  95631.0  95631.0
GALT              21.0  95632.000000   0.000000  95632.0  95632.0  95632.0
GARDEN VALLEY      1.0  95633.000000        NaN  95633.0  95633.0  95633.0
GOLD RIVER         4.0  95670.000000   0.000000  95670.0  95670.0  95670.0
GRANITE BAY        3.0  95746.000000   0.000000  95746.0  95746.0  95746.0
GREENWOOD          1.0  95635.000000        NaN  95635.0  95635.0  95635.0
LINCOLN           72.0  95648.000000   0.000000  95648.0  95648.0  95648.0
LOOMIS             2.0  95650.000000   0.000000  95650.0  95650.0  95650.0
MATHER             1.0  95655.000000        NaN  95655.0  95655.0  95655.0
MEADOW VISTA       1.0  95722.000000        NaN  95722.0  95722.0  95722.0
NORTH HIGHLANDS   21.0  95660.000000   0.000000  95660.0  95660.0  95660.0
ORANGEVALE        11.0  95662.000000   0.000000  95662.0  95662.0  95662.0
PENRYN             1.0  95663.000000        NaN  95663.0  95663.0  95663.0
PLACERVILLE       10.0  95667.000000   0.000000  95667.0  95667.0  95667.0
POLLOCK PINES      3.0  95726.000000   0.000000  95726.0  95726.0  95726.0
RANCHO CORDOVA    28.0  95698.285714  35.809017  95670.0  95670.0  95670.0
RANCHO MURIETA     3.0  95683.000000   0.000000  95683.0  95683.0  95683.0
RIO LINDA         13.0  95673.000000   0.000000  95673.0  95673.0  95673.0
ROCKLIN           17.0  95733.941176  43.348112  95677.0  95677.0  95765.0
ROSEVILLE         48.0  95703.916667  37.271764  95661.0  95678.0  95678.0
SACRAMENTO       439.0  95828.412301   8.303376  95811.0  95823.0  95828.0
SHINGLE SPRINGS    1.0  95682.000000        NaN  95682.0  95682.0  95682.0
SLOUGHHOUSE        1.0  95683.000000        NaN  95683.0  95683.0  95683.0
WALNUT GROVE       1.0  95690.000000        NaN  95690.0  95690.0  95690.0
WEST SACRAMENTO    3.0  95691.000000   0.000000  95691.0  95691.0  95691.0
WILTON             5.0  95693.000000   0.000000  95693.0  95693.0  95693.0

                                    beds            ...   latitude             \
                     75%      max  count      mean  ...        75%        max
city                                                ...
ANTELOPE         95843.0  95843.0   33.0  3.363636  ...  38.720270  38.727657
AUBURN           95603.0  95603.0    5.0  3.000000  ...  38.935579  38.939802
CAMERON PARK     95682.0  95682.0    9.0  2.444444  ...  38.694052  38.697570
CARMICHAEL       95608.0  95608.0   20.0  3.050000  ...  38.662244  38.671995
CITRUS HEIGHTS   95621.0  95621.0   35.0  3.228571  ...  38.715458  38.720868
COOL             95614.0  95614.0    1.0  3.000000  ...  38.905927  38.905927
DIAMOND SPRINGS  95619.0  95619.0    1.0  3.000000  ...  38.688255  38.688255
EL DORADO        95623.0  95623.0    2.0  2.500000  ...  38.677390  38.678758
EL DORADO HILLS  95762.0  95762.0   23.0  3.434783  ...  38.682370  38.706692
ELK GROVE        95758.0  95758.0  114.0  3.359649  ...  38.429067  38.452075
ELVERTA          95626.0  95626.0    4.0  3.250000  ...  38.718145  38.718650
FAIR OAKS        95628.0  95628.0    9.0  3.000000  ...  38.665644  38.667450
FOLSOM           95630.0  95630.0   17.0  3.294118  ...  38.684459  38.703962
FORESTHILL       95631.0  95631.0    1.0  0.000000  ...  39.020808  39.020808
GALT             95632.0  95632.0   21.0  3.333333  ...  38.283085  38.290119
GARDEN VALLEY    95633.0  95633.0    1.0  3.000000  ...  38.842550  38.842550
GOLD RIVER       95670.0  95670.0    4.0  2.250000  ...  38.628874  38.629299
GRANITE BAY      95746.0  95746.0    3.0  4.666667  ...  38.755766  38.779435
GREENWOOD        95635.0  95635.0    1.0  3.000000  ...  38.945357  38.945357
LINCOLN          95648.0  95648.0   72.0  1.000000  ...  38.885835  38.904869
LOOMIS           95650.0  95650.0    2.0  4.000000  ...  38.822156  38.825096
MATHER           95655.0  95655.0    1.0  3.000000  ...  38.547991  38.547991
MEADOW VISTA     95722.0  95722.0    1.0  3.000000  ...  39.008159  39.008159
NORTH HIGHLANDS  95660.0  95660.0   21.0  3.047619  ...  38.697898  38.703550
ORANGEVALE       95662.0  95662.0   11.0  3.363636  ...  38.692620  38.711470
PENRYN           95663.0  95663.0    1.0  3.000000  ...  38.862708  38.862708
PLACERVILLE      95667.0  95667.0   10.0  2.900000  ...  38.743378  38.813546
POLLOCK PINES    95726.0  95726.0    3.0  2.666667  ...  38.764880  38.774910
RANCHO CORDOVA   95742.0  95742.0   28.0  2.642857  ...  38.593685  38.625932
RANCHO MURIETA   95683.0  95683.0    3.0  2.666667  ...  38.502444  38.512602
RIO LINDA        95673.0  95673.0   13.0  2.692308  ...  38.695589  38.702893
ROCKLIN          95765.0  95765.0   17.0  2.764706  ...  38.815493  38.837455
ROSEVILLE        95747.0  95747.0   48.0  2.770833  ...  38.791758  38.808581
SACRAMENTO       95834.0  95864.0  439.0  3.027335  ...  38.635316  38.700051
SHINGLE SPRINGS  95682.0  95682.0    1.0  0.000000  ...  38.643470  38.643470
SLOUGHHOUSE      95683.0  95683.0    1.0  3.000000  ...  38.490447  38.490447
WALNUT GROVE     95690.0  95690.0    1.0  3.000000  ...  38.247659  38.247659
WEST SACRAMENTO  95691.0  95691.0    3.0  0.666667  ...  38.577235  38.584526
WILTON           95693.0  95693.0    5.0  3.400000  ...  38.415298  38.416809

                longitude                                                \
                    count        mean       std         min         25%
city
ANTELOPE             33.0 -121.362247  0.017789 -121.393449 -121.376678
AUBURN                5.0 -121.082133  0.017202 -121.097862 -121.094869
CAMERON PARK          9.0 -120.998527  0.004400 -121.007173 -120.999007
CARMICHAEL           20.0 -121.325816  0.014140 -121.353639 -121.330879
CITRUS HEIGHTS       35.0 -121.300204  0.020861 -121.328555 -121.313622
COOL                  1.0 -120.975169       NaN -120.975169 -120.975169
DIAMOND SPRINGS       1.0 -120.810235       NaN -120.810235 -120.810235
EL DORADO             2.0 -120.861647  0.024790 -120.879176 -120.870411
EL DORADO HILLS      23.0 -121.055980  0.019844 -121.081752 -121.074733
ELK GROVE           114.0 -121.415423  0.035255 -121.484325 -121.443258
ELVERTA               4.0 -121.416466  0.015239 -121.439190 -121.418218
FAIR OAKS             9.0 -121.258199  0.022330 -121.303675 -121.262099
FOLSOM               17.0 -121.139698  0.031034 -121.187100 -121.168578
FORESTHILL            1.0 -120.821518       NaN -120.821518 -120.821518
GALT                 21.0 -121.299923  0.010352 -121.321266 -121.303747
GARDEN VALLEY         1.0 -120.875400       NaN -120.875400 -120.875400
GOLD RIVER            4.0 -121.258031  0.006034 -121.261669 -121.261279
GRANITE BAY           3.0 -121.193948  0.040968 -121.219142 -121.217583
GREENWOOD             1.0 -120.908822       NaN -120.908822 -120.908822
LINCOLN              72.0 -121.290704  0.014451 -121.324691 -121.290275
LOOMIS                2.0 -121.165890  0.046021 -121.198432 -121.182161
MATHER                1.0 -121.280483       NaN -121.280483 -121.280483
MEADOW VISTA          1.0 -121.036230       NaN -121.036230 -121.036230
NORTH HIGHLANDS      21.0 -121.375698  0.003779 -121.382210 -121.378298
ORANGEVALE           11.0 -121.226420  0.019664 -121.254319 -121.242127
PENRYN                1.0 -121.162092       NaN -121.162092 -121.162092
PLACERVILLE          10.0 -120.806783  0.060062 -120.910963 -120.840287
POLLOCK PINES         3.0 -120.602077  0.003903 -120.604760 -120.604316
RANCHO CORDOVA       28.0 -121.267942  0.034797 -121.318669 -121.296598
RANCHO MURIETA        3.0 -121.087465  0.012453 -121.100032 -121.093633
RIO LINDA            13.0 -121.452448  0.009451 -121.463933 -121.463151
ROCKLIN              17.0 -121.251611  0.031637 -121.293609 -121.278798
ROSEVILLE            48.0 -121.304739  0.039746 -121.378718 -121.333798
SACRAMENTO          439.0 -121.443059  0.057484 -121.551704 -121.487118
SHINGLE SPRINGS       1.0 -120.888183       NaN -120.888183 -120.888183
SLOUGHHOUSE           1.0 -121.129337       NaN -121.129337 -121.129337
WALNUT GROVE          1.0 -121.515129       NaN -121.515129 -121.515129
WEST SACRAMENTO       3.0 -121.532576  0.004389 -121.535579 -121.535094
WILTON                5.0 -121.210017  0.023032 -121.240628 -121.228349


                        50%         75%         max
city
ANTELOPE        -121.358939 -121.347887 -121.331555
AUBURN          -121.084340 -121.079018 -121.054575
CAMERON PARK    -120.996602 -120.995739 -120.994949
CARMICHAEL      -121.325952 -121.315412 -121.300055
CITRUS HEIGHTS  -121.305215 -121.295596 -121.246743
COOL            -120.975169 -120.975169 -120.975169
DIAMOND SPRINGS -120.810235 -120.810235 -120.810235
EL DORADO       -120.861647 -120.852882 -120.844118
EL DORADO HILLS -121.058869 -121.036152 -121.015862
ELK GROVE       -121.423975 -121.381279 -121.335541
ELVERTA         -121.409495 -121.407743 -121.407684
FAIR OAKS       -121.258628 -121.240708 -121.230101
FOLSOM          -121.142609 -121.119700 -121.090178
FORESTHILL      -120.821518 -120.821518 -120.821518
GALT            -121.299205 -121.293063 -121.284607
GARDEN VALLEY   -120.875400 -120.875400 -120.875400
GOLD RIVER      -121.260717 -121.257470 -121.249021
GRANITE BAY     -121.216025 -121.181351 -121.146676
GREENWOOD       -120.908822 -120.908822 -120.908822
LINCOLN         -121.289847 -121.289404 -121.231742
LOOMIS          -121.165890 -121.149619 -121.133348
MATHER          -121.280483 -121.280483 -121.280483
MEADOW VISTA    -121.036230 -121.036230 -121.036230
NORTH HIGHLANDS -121.376334 -121.373395 -121.367497
ORANGEVALE      -121.219107 -121.214874 -121.192316
PENRYN          -121.162092 -121.162092 -121.162092
PLACERVILLE     -120.805856 -120.786672 -120.693641
POLLOCK PINES   -120.603872 -120.600735 -120.597599
RANCHO CORDOVA  -121.275561 -121.233521 -121.217611
RANCHO MURIETA  -121.087233 -121.081181 -121.075129
RIO LINDA       -121.452239 -121.444133 -121.435204
ROCKLIN         -121.260979 -121.222801 -121.203600
ROSEVILLE       -121.299674 -121.284248 -121.226494
SACRAMENTO      -121.445006 -121.407556 -121.309243
SHINGLE SPRINGS -120.888183 -120.888183 -120.888183
SLOUGHHOUSE     -121.129337 -121.129337 -121.129337
WALNUT GROVE    -121.515129 -121.515129 -121.515129
WEST SACRAMENTO -121.534609 -121.531074 -121.527539
WILTON          -121.198039 -121.194858 -121.188211

[39 rows x 56 columns]

# Part 5

# Merging, Joining, and Concatenating

There are 3 important ways of combining DataFrames together: 
  - Merging 
  - Joining
  - Concatenating

### Example DataFrames

In [18]:
dafa1 = pd.DataFrame({'CustID': ['101', '102', '103', '104'],
                        'Sales': [13456, 45321, 54385, 53212]},
                        index=[0, 1, 2, 3])

In [19]:
dafa2 = pd.DataFrame({'CustID': ['105', '106', '107', '108'],
                        'Sales': [13456, 54385, 53212, 4534]},
                         index=[4, 5, 6, 7])

In [20]:
dafa3 = pd.DataFrame({'CustID': ['109', '110', '111', '112'],
                        'Sales': [13456, 53212, 4534, 3241]},
                        index=[8, 9, 10, 11])

In [21]:
dafa1

  CustID  Sales
0    101  13456
1    102  45321
2    103  54385
3    104  53212

In [22]:
dafa2

  CustID  Sales
4    105  13456
5    106  54385
6    107  53212
7    108   4534

In [23]:
dafa3

   CustID  Sales
8     109  13456
9     110  53212
10    111   4534
11    112   3241

## Concatenation

Concatenation joins DataFrames basically either by rows or colums(axis=0 or 1).

We also need to ensure dimension sizes of dataframes are the same

In [30]:
pd.concat([dafa1,dafa2,dafa3])

   CustID  Sales
0     101  13456
1     102  45321
2     103  54385
3     104  53212
4     105  13456
5     106  54385
6     107  53212
7     108   4534
8     109  13456
9     110  53212
10    111   4534
11    112   3241

_____
## Example DataFrames

In [37]:
Table1 = pd.DataFrame({'CustID': ['1001', '1002', '1003', '1004'],
                     'Q1': ['101', '102', '103', '104'],
                     'Q2': ['201', '202', '203', '204']})
   
Table2 = pd.DataFrame({'CustID': ['1001', '1006', '1003', '1004'],
                          'Q3': ['301', '302', '303', '304'],
                          'Q4': ['401', '402', '403', '404']})

In [38]:
Table1

  CustID   Q1   Q2
0   1001  101  201
1   1002  102  202
2   1003  103  203
3   1004  104  204

In [39]:
Table2

  CustID   Q3   Q4
0   1001  301  401
1   1006  302  402
2   1003  303  403
3   1004  304  404

## Merging

Just like SQL tables, merge function in python allows us to merge dataframes

In [40]:
pd.merge(Table1,Table2,how='outer',on='CustID')

  CustID   Q1   Q2   Q3   Q4
0   1001  101  201  301  401
1   1002  102  202  NaN  NaN
2   1003  103  203  303  403
3   1004  104  204  304  404
4   1006  NaN  NaN  302  402

In [41]:
pd.merge(Table1,Table2,how='inner', on = 'CustID')

  CustID   Q1   Q2   Q3   Q4
0   1001  101  201  301  401
1   1003  103  203  303  403
2   1004  104  204  304  404

In [42]:
Table1.set_index('CustID',inplace=True)
Table2.set_index('CustID',inplace=True)

In [36]:
Table1.join(Table2,how='inner')

         Q1   Q2   Q3   Q4
CustID
1001    101  201  301  401
1003    103  203  303  403
1004    104  204  304  404

# Part 6

# Operations

Let us discuss some useful Operations using Pandas

### Info on Unique Values

In [32]:
dataframe.columns

Index(['street', 'city', 'zip', 'state', 'beds', 'baths', 'sq__ft', 'type',
       'sale_date', 'price', 'latitude', 'longitude'],
      dtype='object')

In [39]:
dataframe['city'].unique()

array(['SACRAMENTO', 'RANCHO CORDOVA', 'RIO LINDA', 'CITRUS HEIGHTS',
       'NORTH HIGHLANDS', 'ANTELOPE', 'ELK GROVE', 'ELVERTA', 'GALT',
       'CARMICHAEL', 'ORANGEVALE', 'FOLSOM', 'MATHER', 'POLLOCK PINES',
       'GOLD RIVER', 'EL DORADO HILLS', 'RANCHO MURIETA', 'WILTON',
       'GREENWOOD', 'FAIR OAKS', 'CAMERON PARK', 'LINCOLN', 'PLACERVILLE',
       'MEADOW VISTA', 'ROSEVILLE', 'ROCKLIN', 'AUBURN', 'LOOMIS',
       'EL DORADO', 'PENRYN', 'GRANITE BAY', 'FORESTHILL',
       'DIAMOND SPRINGS', 'SHINGLE SPRINGS', 'COOL', 'WALNUT GROVE',
       'GARDEN VALLEY', 'SLOUGHHOUSE', 'WEST SACRAMENTO'], dtype=object)

In [38]:
dataframe['city'].nunique()

39

In [40]:
dataframe['city'].value_counts()

SACRAMENTO         439
ELK GROVE          114
LINCOLN             72
ROSEVILLE           48
CITRUS HEIGHTS      35
ANTELOPE            33
RANCHO CORDOVA      28
EL DORADO HILLS     23
NORTH HIGHLANDS     21
GALT                21
CARMICHAEL          20
ROCKLIN             17
FOLSOM              17
RIO LINDA           13
ORANGEVALE          11
PLACERVILLE         10
CAMERON PARK         9
FAIR OAKS            9
WILTON               5
AUBURN               5
ELVERTA              4
GOLD RIVER           4
WEST SACRAMENTO      3
RANCHO MURIETA       3
GRANITE BAY          3
POLLOCK PINES        3
LOOMIS               2
EL DORADO            2
WALNUT GROVE         1
SHINGLE SPRINGS      1
COOL                 1
FORESTHILL           1
DIAMOND SPRINGS      1
MATHER               1
GREENWOOD            1
GARDEN VALLEY        1
PENRYN               1
SLOUGHHOUSE          1
MEADOW VISTA         1
Name: city, dtype: int64

### Selecting Data

In [44]:
#Select from DataFrame using criteria from multiple columns
newdataframe = dataframe[(dataframe['city'] == 'SACRAMENTO') & (dataframe['baths'] > 3)]

In [50]:
newdataframe

,street,city,zip,state,beds,baths,sq__ft,type,sale_date,price,latitude,longitude
68,7624 BOGEY CT,SACRAMENTO,95828,CA,4,4,2162,Multi-Family,Wed May 21 00:00:00 EDT 2008,195000,38.480090,-121.415102
108,2912 NORCADE CIR,SACRAMENTO,95826,CA,8,4,3612,Multi-Family,Wed May 21 00:00:00 EDT 2008,282400,38.559505,-121.364839
113,10158 CRAWFORD WAY,SACRAMENTO,95827,CA,4,4,2213,Multi-Family,Wed May 21 00:00:00 EDT 2008,297000,38.570300,-121.315735
318,241 LANFRANCO CIR,SACRAMENTO,95835,CA,4,4,3397,Residential,Tue May 20 00:00:00 EDT 2008,465000,38.665696,-121.549437
366,7342 GIGI PL,SACRAMENTO,95828,CA,4,4,1995,Multi-Family,Mon May 19 00:00:00 EDT 2008,120000,38.490704,-121.410176
648,8198 STEVENSON AVE,SACRAMENTO,95828,CA,6,4,2475,Multi-Family,Fri May 16 00:00:00 EDT 2008,159900,38.465271,-121.404260
855,9880 IZILDA CT,SACRAMENTO,95829,CA,5,4,3863,Residential,Fri May 16 00:00:00 EDT 2008,598695,38.453260,-121.325730

### Applying Functions

In [51]:
def profit(a):
    return a*.1

In [52]:
dataframe['price'].apply(profit)

0       5922.2
1       6821.2
2       6888.0
3       6930.7
4       8190.0
5       8992.1
6       9089.5
7       9100.2
8       9490.5
9       9893.7
10     10030.9
11     10625.0
12     10685.2
13     10750.2
14     10875.0
15     11070.0
16     11326.3
17     11625.0
18     12000.0
19     12163.0
20     12200.0
21     12268.2
22     12300.0
23     12410.0
24     12500.0
25     12664.0
26     12728.1
27     12900.0
28     13120.0
29     13200.0
        ...
955    20825.0
956    20831.8
957    20934.7
958    21150.0
959    21200.0
960    21300.0
961    21600.0
962    21602.1
963    21900.0
964    21979.4
965    22000.0
966    22000.0
967    22000.0
968    22000.0
969    22300.0
970    22400.0
971    22400.0
972    22425.2
973    22450.0
974    22500.0
975    22800.0
976    22902.7
977    22950.0
978    23000.0
979    23000.0
980    23242.5
981    23400.0
982    23500.0
983    23530.1
984    23573.8
Name: price, Length: 985, dtype: float64

In [53]:
dataframe['profit'] = dataframe['price'].apply(profit)

In [54]:
dataframe['city'].apply(len)

0      10
1      10
2      10
3      10
4      10
5      10
6      10
7      10
8      14
9       9
10     10
11     10
12     10
13     10
14     10
15     10
16      9
17     14
18     10
19      9
20     14
21     10
22     15
23     10
24     15
25      8
26     10
27     10
28     10
29     10
       ..
955     9
956    15
957     4
958     9
959     8
960    10
961     9
962    10
963    14
964     9
965     9
966     9
967    10
968     4
969    10
970    10
971    10
972    15
973    12
974    10
975     9
976     7
977    10
978    10
979     9
980    10
981    10
982    14
983     9
984    15
Name: city, Length: 985, dtype: int64

In [55]:
dataframe['profit'].sum()

23063210.0

** Permanently Removing a Column**

In [56]:
del dataframe['profit']

In [57]:
dataframe.head()

,street,city,zip,state,beds,baths,sq__ft,type,sale_date,price,latitude,longitude
0,3526 HIGH ST,SACRAMENTO,95838,CA,2,1,836,Residential,Wed May 21 00:00:00 EDT 2008,59222,38.631913,-121.434879
1,51 OMAHA CT,SACRAMENTO,95823,CA,3,1,1167,Residential,Wed May 21 00:00:00 EDT 2008,68212,38.478902,-121.431028
2,2796 BRANCH ST,SACRAMENTO,95815,CA,2,1,796,Residential,Wed May 21 00:00:00 EDT 2008,68880,38.618305,-121.443839
3,2805 JANETTE WAY,SACRAMENTO,95815,CA,2,1,852,Residential,Wed May 21 00:00:00 EDT 2008,69307,38.616835,-121.439146
4,6001 MCMAHON DR,SACRAMENTO,95824,CA,2,1,797,Residential,Wed May 21 00:00:00 EDT 2008,81900,38.519470,-121.435768

** Get column and index names: **

In [58]:
dataframe.index

RangeIndex(start=0, stop=985, step=1)

** Sorting and Ordering a DataFrame:**

In [212]:
dataframe

  SaleType SalesCode
0      big       121
1    small       131
2   medium       141
3      big       151

In [59]:
dataframe.sort_values(by='price') #inplace=False by default

,street,city,zip,state,beds,baths,sq__ft,type,sale_date,price,latitude,longitude
865,3720 VISTA DE MADERA,LINCOLN,95648,CA,3,3,0,Residential,Fri May 16 00:00:00 EDT 2008,1551,38.851645,-121.231742
866,14151 INDIO DR,SLOUGHHOUSE,95683,CA,3,4,5822,Residential,Fri May 16 00:00:00 EDT 2008,2000,38.490447,-121.129337
580,59 E ST,LINCOLN,95648,CA,3,2,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.885794,-121.290281
584,386 1ST ST,LINCOLN,95648,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.886528,-121.288869
585,374 1ST ST,LINCOLN,95648,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.886525,-121.288787
586,116 CRYSTALWOOD WAY,LINCOLN,95648,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.886282,-121.289586
587,108 CRYSTALWOOD WAY,LINCOLN,95648,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.886282,-121.289646
588,100 CRYSTALWOOD WAY,LINCOLN,95648,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.886282,-121.289706
589,55 CRYSTALWOOD CIR,LINCOLN,95648,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.884865,-121.289922
590,51 CRYSTALWOOD CIR,LINCOLN,95648,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.884752,-121.289907
591,47 CRYSTALWOOD CIR,LINCOLN,95648,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.884638,-121.289893
592,43 CRYSTALWOOD CIR,LINCOLN,95648,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.884568,-121.289784
593,39 CRYSTALWOOD CIR,LINCOLN,95648,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.884546,-121.289562
594,35 CRYSTALWOOD CIR,LINCOLN,95648,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.884645,-121.289397
595,31 CRYSTALWOOD CIR,LINCOLN,95648,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.884790,-121.289392
596,27 CRYSTALWOOD CIR,LINCOLN,95648,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.884985,-121.289399
597,23 CRYSTALWOOD CIR,LINCOLN,95648,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.885181,-121.289406
598,19 CRYSTALWOOD CIR,LINCOLN,95648,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.885376,-121.289414
599,15 CRYSTALWOOD CIR,LINCOLN,95648,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.885571,-121.289421
600,7 CRYSTALWOOD CIR,LINCOLN,95648,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.885962,-121.289436
601,7 CRYSTALWOOD CIR,LINCOLN,95648,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.885962,-121.289436
602,3 CRYSTALWOOD CIR,LINCOLN,95648,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.886093,-121.289584
579,51 E ST,LINCOLN,95648,CA,4,2,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.885638,-121.290279
582,63 CRYSTALWOOD CIR,LINCOLN,95648,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.885093,-121.289932
581,75 E ST,LINCOLN,95648,CA,3,2,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.886104,-121.290285
583,398 1ST ST,LINCOLN,95648,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.886530,-121.288952
555,24 CRYSTALWOOD CIR,LINCOLN,95648,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.885132,-121.289405
578,43 E ST,LINCOLN,95648,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.885483,-121.290277
577,35 E ST,LINCOLN,95648,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.885328,-121.290275
576,27 E ST,LINCOLN,95648,CA,0,0,0,Residential,Mon May 19 00:00:00 EDT 2008,4897,38.885173,-121.290270
...,...,...,...,...,...,...,...,...,...,...,...,...
854,203 CASCADE FALLS DR,FOLSOM,95630,CA,4,3,3229,Residential,Fri May 16 00:00:00 EDT 2008,575000,38.703962,-121.187100
853,1165 37TH ST,SACRAMENTO,95816,CA,2,1,1252,Residential,Fri May 16 00:00:00 EDT 2008,575000,38.568438,-121.457854
547,9360 MAGOS RD,WILTON,95693,CA,5,2,3741,Residential,Mon May 19 00:00:00 EDT 2008,579093,38.416809,-121.240628
329,5709 RIVER OAK WAY,CARMICHAEL,95608,CA,4,2,2222,Residential,Tue May 20 00:00:00 EDT 2008,582000,38.602461,-121.330979
153,868 HILDEBRAND CIR,FOLSOM,95630,CA,0,0,0,Residential,Wed May 21 00:00:00 EDT 2008,585000,38.670947,-121.097727
855,9880 IZILDA CT,SACRAMENTO,95829,CA,5,4,3863,Residential,Fri May 16 00:00:00 EDT 2008,598695,38.453260,-121.325730
858,620 KESWICK CT,GRANITE BAY,95746,CA,4,3,2356,Residential,Fri May 16 00:00:00 EDT 2008,600000,38.732096,-121.219142
857,4620 BROMWICH CT,ROCKLIN,95677,CA,4,3,0,Residential,Fri May 16 00:00:00 EDT 2008,600000,38.772672,-121.220232
859,4478 GREENBRAE RD,ROCKLIN,95677,CA,0,0,0,Residential,Fri May 16 00:00:00 EDT 2008,600000,38.781134,-121.222801
856,1800 AVONDALE DR,ROSEVILLE,95747,CA,5,3,0,Residential,Fri May 16 00:00:00 EDT 2008,600000,38.798448,-121.344054
154,6030 PALERMO WAY,EL DORADO HILLS,95762,CA,4,3,0,Residential,Wed May 21 00:00:00 EDT 2008,600000,38.672761,-121.050378
155,4070 REDONDO DR,EL DORADO HILLS,95762,CA,4,3,0,Residential,Wed May 21 00:00:00 EDT 2008,606238,38.666807,-121.064830
860,8432 BRIGGS DR,ROSEVILLE,95747,CA,5,3,3579,Residential,Fri May 16 00:00:00 EDT 2008,610000,38.788610,-121.339495
330,2981 WRINGER DR,ROSEVILLE,95661,CA,4,3,3838,Residential,Tue May 20 00:00:00 EDT 2008,613401,38.735373,-121.227072
331,8616 ROCKPORTE CT,ROSEVILLE,95747,CA,4,2,0,Residential,Tue May 20 00:00:00 EDT 2008,614000,38.742118,-121.359909
861,200 CRADLE MOUNTAIN CT,EL DORADO HILLS,95762,CA,0,0,0,Residential,Fri May 16 00:00:00 EDT 2008,622500,38.647800,-121.030900
548,104 CATLIN CT,FOLSOM,95630,CA,4,3,2660,Residential,Mon May 19 00:00:00 EDT 2008,636000,38.684459,-121.145935
156,4004 CRESTA WAY,SACRAMENTO,95864,CA,3,3,2325,Residential,Wed May 21 00:00:00 EDT 2008,660000,38.591618,-121.370626
549,4734 GIBBONS DR,CARMICHAEL,95608,CA,4,3,3357,Residential,Mon May 19 00:00:00 EDT 2008,668365,38.635580,-121.353639
550,4629 DORCHESTER LN,GRANITE BAY,95746,CA,5,3,2896,Residential,Mon May 19 00:00:00 EDT 2008,676200,38.723545,-121.216025
551,2400 COUNTRYSIDE DR,PLACERVILLE,95667,CA,3,2,2025,Residential,Mon May 19 00:00:00 EDT 2008,677048,38.737452,-120.910963
862,2065 IMPRESSIONIST WAY,EL DORADO HILLS,95762,CA,0,0,0,Residential,Fri May 16 00:00:00 EDT 2008,680000,38.682961,-121.033253
332,4128 HILL ST,FAIR OAKS,95628,CA,5,5,2846,Residential,Tue May 20 00:00:00 EDT 2008,680000,38.641670,-121.262099
552,12901 FURLONG DR,WILTON,95693,CA,5,3,3788,Residential,Mon May 19 00:00:00 EDT 2008,691659,38.413535,-121.188211
333,1409 47TH ST,SACRAMENTO,95819,CA,5,2,2484,Residential,Tue May 20 00:00:00 EDT 2008,699000,38.563244,-121.446876
553,6222 CALLE MONTALVO CIR,GRANITE BAY,95746,CA,5,3,3670,Residential,Mon May 19 00:00:00 EDT 2008,760000,38.779435,-121.146676
157,315 JUMEL CT,EL DORADO HILLS,95762,CA,6,5,0,Residential,Wed May 21 00:00:00 EDT 2008,830000,38.669931,-121.059580
334,3935 EL MONTE DR,LOOMIS,95650,CA,4,4,1624,Residential,Tue May 20 00:00:00 EDT 2008,839000,38.813337,-121.133348
863,2982 ABERDEEN LN,EL DORADO HILLS,95762,CA,4,3,0,Residential,Fri May 16 00:00:00 EDT 2008,879000,38.706692,-121.058869
864,9401 BARREL RACER CT,WILTON,95693,CA,4,3,4400,Residential,Fri May 16 00:00:00 EDT 2008,884790,38.415298,-121.194858

# Part 7

# Data Input and Output

Reading DataFrames from external sources using pd.read functions

## CSV

### CSV Input

### CSV Output

In [220]:
dataframe.to_csv('train2.csv',index=False)    #If index=FALSE then csv does not store index values

## Excel

Using Pandas, one can read excel files, however it can only import data. It does not fetch formulae or any formatting/images/macros and having such things in excel files can crash the python function to crash and not execute successfully.

### Excel Input

In [45]:
dataframe2 = pd.read_excel('pandas-Consumer.xlsx',sheet_name='Data1')

### Excel Output

In [46]:
dataframe.to_excel('Consumer2.xlsx',sheet_name='Sheet1')